"""
Full-pipeline scenario test: diffuse large B-cell lymphoma (DLBCL), GCB subtype, Ann Arbor
Stage III -- a hematologic malignancy with no surgical arm and a different staging system
(Ann Arbor, not AJCC TNM) than either the original breast-cancer demo case or the lung-cancer
scenario. Drives the real running app through a real browser across the full role pipeline:
Front Desk registration + document upload -> Nurse Navigator intake -> Medical Oncologist
review/orders -> Radiology/Pathology/Lab finalize -> Staging (with the deliberate laterality
contradiction NEXUS must flag) -> MDT (referral, Coordinator schedule + external access,
External MDT Specialist opinion, oncologist recommendation, Coordinator disposition) ->
Treatment Plan (R-CHOP) -> Treatment Order + Clearance (Cycle 1) -> Lab posts abnormal platelets
-> oncologist holds -> repeat labs clear -> Cycle 2 -> Care Plan -> Financial Counsellor ->
Patient Liaison -> Patient History cross-role visibility -> negative-permission checks.

Source documents: data/scenarios/lymphoma/*.pdf (generated by tools/generate_scenario_docs.py).
OCR (extract_document) and LLM fact extraction (extract_clinical_facts) are mocked -- see
module docstring precedent in tests/integration/test_patient_document_ocr.py and this
session's tests/conftest.py::_no_live_groq_calls -- keyed by each file's exact bytes so a real
upload of a real generated PDF still drives realistic classification/fact extraction without
a live OCR model or LLM call.
"""
import hashlib
import os
import re

import pytest

from tests.e2e.conftest import login_as

pytestmark = pytest.mark.e2e

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DOC_DIR = os.path.join(REPO_ROOT, "data", "scenarios", "lymphoma")


def _doc_path(filename):
    return os.path.join(DOC_DIR, filename)


# filename -> (ocr_text, facts) -- facts use the exact shape extract_clinical_facts returns.
_DOC_SPEC = {
    "01_Referral_Letter.pdf": (
        "Referral letter. Please evaluate the right cervical lymphadenopathy and advise oncology management.",
        [{"fact_type": "LATERALITY", "value": "Right", "verbatim": "right cervical", "confidence": 0.7}],
    ),
    "02_Excisional_Node_Biopsy_Pathology.pdf": (
        "Surgical pathology biopsy report. Histopathology: diffuse large B-cell lymphoma, germinal centre B-cell type. Left cervical node.",
        [{"fact_type": "HISTOLOGY", "value": "Diffuse large B-cell lymphoma", "verbatim": "diffuse large B-cell lymphoma", "confidence": 0.95},
         {"fact_type": "LATERALITY", "value": "Left", "verbatim": "left cervical node", "confidence": 0.9}],
    ),
    "03_Immunohistochemistry_Report.pdf": (
        "Immunohistochemistry and biomarker report. CD20 positive. CD10 positive. BCL6 positive. Ki-67 approximately 85%.",
        [{"fact_type": "BIOMARKER_RESULT", "value": "CD20 positive, CD10 positive, BCL6 positive, Ki-67 ~85%", "verbatim": "CD20 positive", "confidence": 0.9}],
    ),
    "04_Baseline_Laboratory_Report.pdf": (
        "Clinical pathology laboratory. Hemoglobin 11.4 g/dL. LDH elevated 410 U/L. Renal / liver profile within range.",
        [{"fact_type": "LAB_RESULT", "value": "Hb 11.4 g/dL, LDH 410 U/L (elevated)", "verbatim": "LDH elevated 410 U/L", "confidence": 0.8}],
    ),
    "05_Baseline_Echocardiogram.pdf": (
        "Echocardiogram report. LVEF 60%. Preserved left ventricular systolic function.",
        [{"fact_type": "LAB_RESULT", "value": "LVEF 60%", "verbatim": "LVEF 60%", "confidence": 0.8}],
    ),
    "06_PET_CT_Staging_Report.pdf": (
        "Radiodiagnosis PET-CT. Impression: Ann Arbor Stage III diffuse large B-cell lymphoma, left cervical, left axillary and splenic involvement.",
        [{"fact_type": "N_EVIDENCE", "value": "Left cervical and left axillary nodal involvement", "verbatim": "left cervical, left axillary", "confidence": 0.85},
         {"fact_type": "M_EVIDENCE", "value": "No disease below diaphragm outside spleen", "verbatim": "Ann Arbor Stage III", "confidence": 0.8}],
    ),
    "07_Pre_Cycle2_CBC.pdf": (
        "Clinical pathology laboratory. Hemoglobin 10.1 g/dL. Platelets 68 x10^9/L. ANC 2.8 x10^9/L.",
        [{"fact_type": "LAB_RESULT", "value": "Platelets 68 x10^9/L (below threshold)", "verbatim": "Platelets 68 x10^9/L", "confidence": 0.85}],
    ),
    "08_Repeat_CBC_After_Delay.pdf": (
        "Clinical pathology laboratory. Platelets 165 x10^9/L. ANC 3.0 x10^9/L.",
        [{"fact_type": "LAB_RESULT", "value": "Platelets 165 x10^9/L (recovered)", "verbatim": "Platelets 165 x10^9/L", "confidence": 0.85}],
    ),
}


def _install_document_mocks(monkeypatch):
    """Maps each generated scenario PDF's exact bytes to known OCR text + facts, so a real
    upload of a real file drives classify_document (real, keyword-based) and a mocked
    extract_document/extract_clinical_facts (bypassing OCR/LLM) with realistic content."""
    import app.routers.cca as cca_module

    by_hash = {}
    for filename, (text, facts) in _DOC_SPEC.items():
        with open(_doc_path(filename), "rb") as f:
            content = f.read()
        by_hash[hashlib.sha256(content).hexdigest()] = (text, facts)

    def _fake_extract_document(content, content_type):
        text, _facts = by_hash.get(hashlib.sha256(content).hexdigest(), ("", []))
        return {"text": text, "page_count": 1}

    def _fake_extract_clinical_facts(document_text):
        for text, facts in by_hash.values():
            if text == document_text:
                return facts
        return []

    monkeypatch.setattr(cca_module, "extract_document", _fake_extract_document)
    monkeypatch.setattr(cca_module, "extract_clinical_facts", _fake_extract_clinical_facts)


@pytest.fixture
def lymphoma_org_users(make_user):
    oncologist = make_user(email="onc@lymphomascenario.com", role="CCAMedicalOncologist")
    org_id = oncologist.organization_id
    return {
        "front_desk": make_user(email="frontdesk@lymphomascenario.com", role="CCAFrontDesk", organization_id=org_id),
        "nurse": make_user(email="nurse@lymphomascenario.com", role="CCANurseNavigator", organization_id=org_id),
        "oncologist": oncologist,
        "radiologist": make_user(email="rad@lymphomascenario.com", role="CCARadiologist", organization_id=org_id),
        "pathologist": make_user(email="path@lymphomascenario.com", role="CCAPathologist", organization_id=org_id),
        "lab": make_user(email="lab@lymphomascenario.com", role="CCALabPhlebotomy", organization_id=org_id),
        "coordinator": make_user(email="mdt@lymphomascenario.com", role="CCAMDTCoordinator", organization_id=org_id),
        "external": make_user(email="external@lymphomascenario.com", role="CCAExternalMDTSpecialist", organization_id=org_id),
        "financial": make_user(email="fin@lymphomascenario.com", role="CCAFinancialCounsellor", organization_id=org_id),
        "liaison": make_user(email="liaison@lymphomascenario.com", role="CCAPatientLiaison", organization_id=org_id),
    }


def test_lymphoma_full_pipeline(js_page, live_server_url, lymphoma_org_users, monkeypatch):
    _install_document_mocks(monkeypatch)
    js_page.on("dialog", lambda d: d.accept())
    users = lymphoma_org_users

    # ---- 1. Front Desk: register patient + upload all source documents ----
    login_as(js_page, live_server_url, users["front_desk"], landing_path="/frontdesk.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate("showTab('registration')")
    js_page.wait_for_timeout(200)
    js_page.evaluate("startNewRegistrationWizard()")
    js_page.wait_for_timeout(400)

    js_page.evaluate("goToWizardStep(1)")
    js_page.fill("#wiz-fullname", "Kavya Reddy")
    js_page.fill("#wiz-age", "41")
    js_page.select_option("#wiz-sex", "Female")
    js_page.fill("#wiz-mobile", "+91 90000 30003")

    js_page.evaluate("goToWizardStep(4)")
    for filename in _DOC_SPEC.keys():
        doc_type = "Previous radiology report" if "PET_CT" in filename else (
            "Previous pathology report" if "Pathology" in filename or "Immunohistochemistry" in filename else "Other"
        )
        js_page.select_option("#wiz-doc-type", doc_type)
        js_page.set_input_files("#wiz-doc-file", _doc_path(filename))
        js_page.wait_for_timeout(150)

    js_page.evaluate("goToWizardStep(5)")
    js_page.click('button[onclick="submitFullRegistration()"]')
    js_page.wait_for_timeout(2500)
    assert js_page.js_errors == [], f"registration errors: {js_page.js_errors}"

    from app.main import SessionLocal
    from app.models_cca import CCAPatient

    db = SessionLocal()
    try:
        patient = db.query(CCAPatient).filter(CCAPatient.name == "Kavya Reddy").order_by(CCAPatient.id.desc()).first()
        assert patient is not None, "patient was not registered"
        patient_id = patient.id
    finally:
        db.close()

    # ---- 2. Nurse Navigator: intake ----
    login_as(js_page, live_server_url, users["nurse"], landing_path="/nurse_navigator.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate(f"""
        (async () => {{
            const enc = await Api.post(`/cca/patients/{patient_id}/encounters`, {{}});
            window.__nurseEncounterId = enc.encounter.id;
            await Api.post(`/cca/encounters/${{window.__nurseEncounterId}}/intake`, {{
                patient_id: {patient_id},
                chief_complaint: 'Painless enlarging neck swelling for 2 months with night sweats and weight loss.',
                bp_systolic: 118, bp_diastolic: 76, heart_rate: 82, oxygen_sat: 98,
                ecog: 1, pain_score: 0,
            }});
        }})()
    """)
    js_page.wait_for_timeout(1000)
    assert js_page.js_errors == [], f"nurse intake errors: {js_page.js_errors}"

    # ---- 3. Medical Oncologist: review Patient History, reconcile contradiction, order tests ----
    login_as(js_page, live_server_url, users["oncologist"], landing_path="/medical_oncologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate("showTab('nexus')")
    js_page.wait_for_timeout(1200)
    nexus_html = js_page.inner_html("#nexus-brief-container")
    print("\n\n===== NEXUS BRIEF (lymphoma) =====\n", nexus_html[:4000], "\n===== END =====\n")

    js_page.evaluate(f"""
        (async () => {{
            await Api.post('/cca/orders', {{ patient_id: {patient_id}, order_type: 'RADIOLOGY', item_name: 'PET-CT Staging', clinical_indication: 'Staging workup for DLBCL.' }});
            await Api.post('/cca/orders', {{ patient_id: {patient_id}, order_type: 'PATHOLOGY', item_name: 'Excisional Lymph Node Biopsy', clinical_indication: 'Tissue diagnosis for cervical lymphadenopathy.' }});
            await Api.post('/cca/orders', {{ patient_id: {patient_id}, order_type: 'LAB', item_name: 'Baseline CBC/LDH', clinical_indication: 'Baseline treatment readiness.' }});
        }})()
    """)
    js_page.wait_for_timeout(800)
    assert js_page.js_errors == [], f"order raising errors: {js_page.js_errors}"

    from app.models_cca import CCAOrder

    db = SessionLocal()
    try:
        rad_order = db.query(CCAOrder).filter(CCAOrder.patient_id == patient_id, CCAOrder.order_type == "RADIOLOGY").first()
        path_order = db.query(CCAOrder).filter(CCAOrder.patient_id == patient_id, CCAOrder.order_type == "PATHOLOGY").first()
        assert rad_order and path_order
        rad_order_id, path_order_id = rad_order.id, path_order.id
    finally:
        db.close()

    # ---- 4. Radiology finalizes PET-CT ----
    login_as(js_page, live_server_url, users["radiologist"], landing_path="/radiologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate("showTab('imaging')")
    js_page.wait_for_timeout(600)
    js_page.evaluate(f"openImagingOrder({rad_order_id})")
    js_page.wait_for_timeout(400)
    js_page.fill("#img-findings", "Hypermetabolic left cervical, left axillary and splenic lesions. No disease below the diaphragm outside the spleen.")
    js_page.fill("#img-impression", "Findings consistent with Ann Arbor Stage III diffuse large B-cell lymphoma.")
    js_page.click(f'button[onclick="submitImagingReport({rad_order_id})"]')
    js_page.wait_for_timeout(700)
    js_page.click('button:has-text("Finalize Report")')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"radiology finalize errors: {js_page.js_errors}"

    # ---- 5. Pathology finalizes excisional node biopsy ----
    login_as(js_page, live_server_url, users["pathologist"], landing_path="/pathologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate("showTab('pathology')")
    js_page.wait_for_timeout(600)
    js_page.evaluate(f"openPathologyOrder({path_order_id})")
    js_page.wait_for_timeout(400)
    js_page.fill("#path-findings", "Diffuse large B-cell lymphoma, germinal centre B-cell type. CD20+, CD10+, BCL6+, Ki-67 ~85%. Left cervical node.")
    js_page.click(f'button[onclick="submitPathologyReport({path_order_id})"]')
    js_page.wait_for_timeout(700)
    js_page.click('button:has-text("Finalize Report")')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"pathology finalize errors: {js_page.js_errors}"

    # ---- 6. Lab collects + results baseline CBC/LDH ----
    login_as(js_page, live_server_url, users["lab"], landing_path="/laboratory.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate("showTab('lab')")
    js_page.wait_for_timeout(600)

    from app.models_cca import CCAOrder as CCAOrderModel

    db = SessionLocal()
    try:
        lab_order = db.query(CCAOrderModel).filter(CCAOrderModel.patient_id == patient_id, CCAOrderModel.order_type == "LAB").order_by(CCAOrderModel.id.desc()).first()
        lab_order_id = lab_order.id
    finally:
        db.close()

    js_page.click(f'button[onclick="submitLabCollect({lab_order_id})"]')
    js_page.wait_for_timeout(500)
    js_page.evaluate(f"openLabResultInline({lab_order_id})")
    js_page.wait_for_timeout(300)
    js_page.fill(f"#lab-findings-{lab_order_id}", "Hb 11.4 g/dL, Platelets 260 x10^9/L, LDH 410 U/L (elevated).")
    js_page.click(f'button[onclick="submitLabResult({lab_order_id})"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"lab result errors: {js_page.js_errors}"

    # ---- 7. Oncologist: confirm staging (Ann Arbor, not AJCC TNM) ----
    login_as(js_page, live_server_url, users["oncologist"], landing_path="/medical_oncologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate("showTab('staging')")
    js_page.wait_for_timeout(800)
    js_page.fill("#stg-t", "N/A")
    js_page.fill("#stg-n", "N/A")
    js_page.fill("#stg-m", "N/A")
    js_page.fill("#stg-value", "Ann Arbor Stage III")
    js_page.fill("#stg-group", "Stage III")
    js_page.fill("#stg-reason", "PET-CT and excisional node biopsy confirm Ann Arbor Stage III DLBCL, GCB subtype, with left cervical/axillary/splenic involvement.")
    js_page.click('button[onclick="submitStagingConfirm()"]')
    js_page.wait_for_timeout(800)
    assert js_page.js_errors == [], f"staging confirm errors: {js_page.js_errors}"

    print("\n\n===== SCENARIO CHECKPOINT: registration through staging complete for patient", patient_id, "=====\n")

    # ---- 8. Oncologist: refer to MDT ----
    js_page.evaluate("showTab('mdt')")
    js_page.wait_for_timeout(600)
    js_page.fill("#mdt-question", "Optimal first-line regimen for GCB-subtype DLBCL, Ann Arbor Stage III with elevated LDH?")
    js_page.click('button[onclick="submitMdtCase()"]')
    js_page.wait_for_timeout(800)
    assert js_page.js_errors == [], f"MDT referral errors: {js_page.js_errors}"

    from app.models_cca import MDTCase

    db = SessionLocal()
    try:
        case = db.query(MDTCase).filter(MDTCase.patient_id == patient_id).order_by(MDTCase.id.desc()).first()
        assert case is not None
        case_id = case.id
    finally:
        db.close()

    # ---- 9. MDT Coordinator: schedule, grant external access ----
    login_as(js_page, live_server_url, users["coordinator"], landing_path="/mdt_coordinator.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate("showTab('mdt')")
    js_page.wait_for_timeout(700)
    js_page.evaluate(f"openMdtCase({case_id}, {patient_id})")
    js_page.wait_for_timeout(500)
    js_page.fill(f"#mdtc-date-{case_id}", "2026-09-16")
    js_page.fill(f"#mdtc-time-{case_id}", "10:00")
    js_page.click(f'button[onclick="submitMdtSchedule({case_id})"]')
    js_page.wait_for_timeout(700)

    js_page.evaluate(f"openMdtCase({case_id}, {patient_id})")
    js_page.wait_for_timeout(500)
    js_page.fill(f"#mdtc-extname-{case_id}", "Dr. Haemato-oncology Second Opinion")
    js_page.fill(f"#mdtc-extemail-{case_id}", users["external"].email)
    js_page.click(f'button[onclick="submitGrantExternalAccess({case_id})"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"coordinator MDT errors: {js_page.js_errors}"

    # ---- 10. External MDT Specialist: submit opinion ----
    login_as(js_page, live_server_url, users["external"], landing_path="/external_mdt_specialist.html")
    js_page.wait_for_timeout(600)
    js_page.click(f'button[onclick="loadOpinionsAndForm({case_id})"]')
    js_page.wait_for_timeout(400)
    js_page.fill(f"#opinion-rec-{case_id}", "Agree with standard R-CHOP x6, interim PET-CT after cycle 4 to assess response.")
    js_page.fill(f"#opinion-rationale-{case_id}", "GCB subtype and IPI risk profile support standard R-CHOP without escalation.")
    js_page.select_option(f"#opinion-certainty-{case_id}", "High")
    js_page.click(f'button[onclick="submitOpinion({case_id})"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"external specialist errors: {js_page.js_errors}"

    # ---- 11. Oncologist: record recommendation, Coordinator: disposition (Accept) ----
    login_as(js_page, live_server_url, users["oncologist"], landing_path="/medical_oncologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate("showTab('mdt')")
    js_page.wait_for_timeout(600)
    js_page.click(f'button[onclick="openRecommendationForm({case_id})"]')
    js_page.wait_for_timeout(300)
    js_page.fill(f"#mdt-rec-text-{case_id}", "Proceed with R-CHOP (rituximab-CHOP) every 3 weeks for 6 cycles, interim PET-CT after cycle 4.")
    js_page.click(f'button[onclick="submitMdtRecommendation({case_id})"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"MDT recommendation errors: {js_page.js_errors}"

    login_as(js_page, live_server_url, users["coordinator"], landing_path="/mdt_coordinator.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate("showTab('mdt')")
    js_page.wait_for_timeout(700)
    js_page.evaluate(f"openMdtCase({case_id}, {patient_id})")
    js_page.wait_for_timeout(500)
    js_page.click(f'button[onclick="submitMdtCoordinatorDisposition({case_id}, \'ACCEPT\')"]')
    js_page.wait_for_timeout(800)
    assert js_page.js_errors == [], f"coordinator disposition errors: {js_page.js_errors}"

    # ---- 12. Oncologist: create + sign Treatment Plan (R-CHOP) ----
    login_as(js_page, live_server_url, users["oncologist"], landing_path="/medical_oncologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate("showTab('treatmentplan')")
    js_page.wait_for_timeout(700)
    js_page.fill("#tp-protocol", "R-CHOP (Rituximab-CHOP)")
    js_page.fill("#tp-sessions", "6")
    js_page.click('button[onclick="submitCreateTreatmentPlan()"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"create treatment plan errors: {js_page.js_errors}"

    js_page.click('button[onclick="signTreatmentPlanSubmit()"]')
    js_page.wait_for_timeout(800)
    assert js_page.js_errors == [], f"sign treatment plan errors: {js_page.js_errors}"

    from app.models_cca import TreatmentPlan

    db = SessionLocal()
    try:
        plan = db.query(TreatmentPlan).filter(TreatmentPlan.patient_id == patient_id).order_by(TreatmentPlan.id.desc()).first()
        assert plan.status == "ACTIVE"
        plan_id = plan.id
    finally:
        db.close()

    # ---- 13. Cycle 1: create + sign Treatment Order, clear standard dose ----
    js_page.evaluate("loadTreatmentPlanView()")
    js_page.wait_for_timeout(600)
    js_page.click(f'button[onclick="submitCreateTreatmentOrder({plan_id})"]')
    js_page.wait_for_timeout(700)
    html = js_page.inner_html("#treatmentplan-content")
    order_id = int(re.search(r"submitSignTreatmentOrder\((\d+)\)", html).group(1))
    js_page.click(f'button[onclick="submitSignTreatmentOrder({order_id})"]')
    js_page.wait_for_timeout(700)
    js_page.select_option("#clearance-decision-onc", "CLEARED")
    js_page.fill("#clearance-reason-onc", "Baseline counts within tolerance; standard dose cycle 1 R-CHOP.")
    js_page.click(f'button[onclick="submitClearanceOnc({order_id})"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"cycle 1 clearance errors: {js_page.js_errors}"

    # ---- 14. Oncologist orders pre-cycle-2 CBC; Lab posts low platelets; oncologist HOLDs ----
    js_page.evaluate(f"""
        (async () => {{
            await Api.post('/cca/orders', {{ patient_id: {patient_id}, order_type: 'LAB', item_name: 'Pre-Cycle 2 CBC', clinical_indication: 'Pre-R-CHOP cycle 2 count check.' }});
        }})()
    """)
    js_page.wait_for_timeout(500)

    login_as(js_page, live_server_url, users["lab"], landing_path="/laboratory.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate("showTab('lab')")
    js_page.wait_for_timeout(600)

    from app.models_cca import CCAOrder as CCAOrderModel2

    db = SessionLocal()
    try:
        cbc_order = db.query(CCAOrderModel2).filter(CCAOrderModel2.patient_id == patient_id, CCAOrderModel2.item_name == "Pre-Cycle 2 CBC").first()
        cbc_order_id = cbc_order.id
    finally:
        db.close()

    js_page.evaluate("loadLabWorklist()")
    js_page.wait_for_timeout(500)
    js_page.click(f'button[onclick="submitLabCollect({cbc_order_id})"]')
    js_page.wait_for_timeout(500)
    js_page.evaluate(f"openLabResultInline({cbc_order_id})")
    js_page.wait_for_timeout(300)
    js_page.fill(f"#lab-findings-{cbc_order_id}", "Platelets 68 x10^9/L -- below institutional treatment threshold for R-CHOP cycle 2. Hb 10.1 g/dL, ANC 2.8 x10^9/L.")
    js_page.check(f"#lab-critical-{cbc_order_id}")
    js_page.click(f'button[onclick="submitLabResult({cbc_order_id})"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"pre-cycle-2 lab errors: {js_page.js_errors}"

    login_as(js_page, live_server_url, users["oncologist"], landing_path="/medical_oncologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate("showTab('treatmentplan')")
    js_page.wait_for_timeout(700)
    html = js_page.inner_html("#treatmentplan-content")
    assert "Create Treatment Order" in html, f"expected a fresh order slot for cycle 2:\n{html[:2000]}"
    js_page.click(f'button[onclick="submitCreateTreatmentOrder({plan_id})"]')
    js_page.wait_for_timeout(700)
    html = js_page.inner_html("#treatmentplan-content")
    cycle2_order_id = int(re.search(r"submitSignTreatmentOrder\((\d+)\)", html).group(1))
    js_page.click(f'button[onclick="submitSignTreatmentOrder({cycle2_order_id})"]')
    js_page.wait_for_timeout(700)
    js_page.select_option("#clearance-decision-onc", "HELD")
    js_page.fill("#clearance-reason-onc", "Platelets 68 x10^9/L -- below threshold for cycle 2 R-CHOP. Holding, repeat CBC ordered.")
    js_page.click(f'button[onclick="submitClearanceOnc({cycle2_order_id})"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"cycle 2 hold errors: {js_page.js_errors}"

    from app.models_cca import TreatmentSession

    db = SessionLocal()
    try:
        session = db.query(TreatmentSession).filter(TreatmentSession.treatment_plan_id == plan_id).order_by(TreatmentSession.id.desc()).first()
        assert session.status == "HELD"
    finally:
        db.close()

    # ---- 15. Repeat CBC recovers; oncologist clears cycle 2 ----
    login_as(js_page, live_server_url, users["oncologist"], landing_path="/medical_oncologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate(f"""
        (async () => {{
            await Api.post('/cca/orders', {{ patient_id: {patient_id}, order_type: 'LAB', item_name: 'Repeat CBC', clinical_indication: 'Reassessment after platelet hold.' }});
        }})()
    """)
    js_page.wait_for_timeout(500)

    login_as(js_page, live_server_url, users["lab"], landing_path="/laboratory.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate("showTab('lab')")
    js_page.wait_for_timeout(600)

    db = SessionLocal()
    try:
        repeat_order = db.query(CCAOrderModel2).filter(CCAOrderModel2.patient_id == patient_id, CCAOrderModel2.item_name == "Repeat CBC").first()
        repeat_order_id = repeat_order.id
    finally:
        db.close()

    js_page.evaluate("loadLabWorklist()")
    js_page.wait_for_timeout(500)
    js_page.click(f'button[onclick="submitLabCollect({repeat_order_id})"]')
    js_page.wait_for_timeout(500)
    js_page.evaluate(f"openLabResultInline({repeat_order_id})")
    js_page.wait_for_timeout(300)
    js_page.fill(f"#lab-findings-{repeat_order_id}", "Platelets 165 x10^9/L, ANC 3.0 x10^9/L -- recovered.")
    js_page.click(f'button[onclick="submitLabResult({repeat_order_id})"]')
    js_page.wait_for_timeout(700)

    login_as(js_page, live_server_url, users["oncologist"], landing_path="/medical_oncologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate("showTab('treatmentplan')")
    js_page.wait_for_timeout(700)
    html = js_page.inner_html("#treatmentplan-content")
    assert "Decide Treatment Clearance" in html, f"expected the still-signed order's clearance form after HELD:\n{html[:2000]}"
    js_page.select_option("#clearance-decision-onc", "CLEARED")
    js_page.fill("#clearance-reason-onc", "Repeat CBC recovered (Platelets 165, ANC 3.0). Cleared for standard dose cycle 2.")
    js_page.click(f'button[onclick="submitClearanceOnc({cycle2_order_id})"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"cycle 2 clearance-after-recovery errors: {js_page.js_errors}"

    from app.models_cca import TreatmentOrder

    db = SessionLocal()
    try:
        db_order = db.query(TreatmentOrder).filter(TreatmentOrder.id == cycle2_order_id).first()
        assert db_order.status == "EXECUTED"
    finally:
        db.close()

    # ---- 16. Oncologist: create Care Plan (no surgical component -- hematologic, no surgery arm) ----
    js_page.evaluate("showTab('careplan')")
    js_page.wait_for_timeout(700)
    cp_html = js_page.inner_html("#careplan-content")
    assert "Create Care Plan" in cp_html, f"no create-care-plan form:\n{cp_html[:2000]}"
    js_page.fill("#cp-create-systemic", "R-CHOP x6 cycles every 3 weeks, interim PET-CT after cycle 4, end-of-treatment PET-CT for response.")
    js_page.click('button[onclick="submitCreateCarePlan()"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"care plan creation errors: {js_page.js_errors}"

    from app.models_cca import CarePlan

    db = SessionLocal()
    try:
        cp = db.query(CarePlan).filter(CarePlan.patient_id == patient_id).first()
        assert cp is not None and cp.status == "ACTIVE"
    finally:
        db.close()

    # ---- 17. Financial Counsellor ----
    login_as(js_page, live_server_url, users["financial"], landing_path="/patient_financial_services.html")
    js_page.wait_for_timeout(600)
    assert js_page.js_errors == [], f"financial counsellor load errors: {js_page.js_errors}"

    # ---- 18. Patient Liaison ----
    login_as(js_page, live_server_url, users["liaison"], landing_path="/patient_liaison.html")
    js_page.wait_for_timeout(600)
    js_page.evaluate("showTab('coordination')")
    js_page.wait_for_timeout(600)
    assert js_page.js_errors == [], f"patient liaison load errors: {js_page.js_errors}"

    # ---- 19. Patient History cross-role visibility ----
    login_as(js_page, live_server_url, users["coordinator"], landing_path="/mdt_coordinator.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate("showTab('history')")
    js_page.wait_for_timeout(1000)
    final_history_html = js_page.inner_html("#history-content")
    assert "Investigations Ordered" in final_history_html
    assert "Repeat CBC" in final_history_html or "Pre-Cycle 2 CBC" in final_history_html
    assert js_page.js_errors == [], f"final patient history errors: {js_page.js_errors}"

    # ---- 20. Negative permission checks ----
    import requests
    from tests.e2e.conftest import mint_tokens

    fd_tokens = mint_tokens(users["front_desk"])
    resp = requests.get(
        f"{live_server_url}/api/cca/patients/{patient_id}/case-summary",
        headers={"Authorization": f"Bearer {fd_tokens['access_token']}"},
    )
    assert resp.status_code == 403, f"Front Desk should not access clinical case-summary, got {resp.status_code}"

    ext_tokens = mint_tokens(users["external"])
    resp2 = requests.get(
        f"{live_server_url}/api/cca/patients",
        headers={"Authorization": f"Bearer {ext_tokens['access_token']}"},
    )
    assert resp2.status_code == 403, f"External MDT Specialist should not browse the patient list, got {resp2.status_code}: {resp2.text[:300]}"

    print("\n\n===== LYMPHOMA SCENARIO: FULL PIPELINE PASSED for patient", patient_id, "=====\n")
