"""
Full-pipeline scenario test: locally advanced cervical carcinoma, FIGO Stage IIB, HPV-16
positive -- radiation-led (concurrent chemoradiation), no surgical arm, and genuinely exercises
the Radiation Oncologist role (untouched by the lung/lymphoma scenarios) alongside the Medical
Oncologist's concurrent weekly cisplatin. Also exercises a Care Plan built from TWO Treatment
Plans across different modalities (Radiation + Systemic) for the same patient -- a code path
neither the lung nor lymphoma scenario exercised, since both had only one active Treatment Plan.

Drives the real running app through a real browser across the full role pipeline: Front Desk
registration + document upload -> Nurse Navigator intake -> Medical Oncologist review/orders
-> Radiology/Pathology/Lab finalize -> Staging (FIGO, with the deliberate site contradiction
NEXUS must flag) -> MDT (referral, Coordinator schedule + external access, External MDT
Specialist opinion, oncologist recommendation, Coordinator disposition) -> Radiation Oncologist
creates + signs a Radiation Therapy Treatment Plan -> Medical Oncologist creates + signs a
concurrent Systemic Therapy Treatment Plan (weekly cisplatin) -> Treatment Order + Clearance
(Week 1) -> Lab posts anemia -> oncologist holds -> repeat labs clear -> Week 3 -> Care Plan
built from both Treatment Plans -> Financial Counsellor -> Patient Liaison -> Patient History
cross-role visibility -> negative-permission checks.

Source documents: data/scenarios/cervical/*.pdf (generated by tools/generate_scenario_docs.py).
OCR (extract_document) and LLM fact extraction (extract_clinical_facts) are mocked -- see
module docstring precedent in tests/integration/test_patient_document_ocr.py and this
session's tests/conftest.py::_no_live_groq_calls -- keyed by each file's exact bytes so a real
upload of a real generated PDF still drives realistic classification/fact extraction without
a live OCR model or LLM call.
"""
import hashlib
import os
import re

import pytest

from tests.e2e.conftest import login_as

pytestmark = pytest.mark.e2e

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DOC_DIR = os.path.join(REPO_ROOT, "data", "scenarios", "cervical")


def _doc_path(filename):
    return os.path.join(DOC_DIR, filename)


# filename -> (ocr_text, facts) -- facts use the exact shape extract_clinical_facts returns.
_DOC_SPEC = {
    "01_Referral_Letter.pdf": (
        "Referral letter. Please evaluate the endometrial mass and advise oncology management.",
        [{"fact_type": "PRIMARY_SITE", "value": "Endometrium", "verbatim": "endometrial mass", "confidence": 0.6}],
    ),
    "02_Cervical_Biopsy_Pathology.pdf": (
        "Surgical pathology biopsy report. Histopathology: squamous cell carcinoma of the cervix, moderately differentiated.",
        [{"fact_type": "HISTOLOGY", "value": "Squamous cell carcinoma of the cervix", "verbatim": "squamous cell carcinoma of the cervix", "confidence": 0.95},
         {"fact_type": "PRIMARY_SITE", "value": "Cervix", "verbatim": "cervix", "confidence": 0.9}],
    ),
    "03_HPV_Test_Report.pdf": (
        "High-risk HPV genotyping. HPV-16 detected, high-risk positive.",
        [{"fact_type": "BIOMARKER_RESULT", "value": "HPV-16 positive", "verbatim": "HPV-16 detected", "confidence": 0.9}],
    ),
    "04_Pelvic_MRI_Report.pdf": (
        "Radiodiagnosis pelvic MRI. Impression: cervical mass 4.5 cm with left parametrial extension, FIGO Stage IIB.",
        [{"fact_type": "T_EVIDENCE", "value": "4.5 cm cervical mass with parametrial extension", "verbatim": "4.5 cm with left parametrial extension", "confidence": 0.85}],
    ),
    "05_PET_CT_Staging_Report.pdf": (
        "Radiodiagnosis PET-CT. Impression: locally advanced cervical carcinoma with left pelvic sidewall nodal involvement, no distant metastasis.",
        [{"fact_type": "N_EVIDENCE", "value": "Left pelvic sidewall lymphadenopathy", "verbatim": "left pelvic sidewall lymph nodes", "confidence": 0.85},
         {"fact_type": "M_EVIDENCE", "value": "No distant metastatic disease", "verbatim": "no distant metastatic disease", "confidence": 0.85}],
    ),
    "06_Baseline_Laboratory_Report.pdf": (
        "Clinical pathology laboratory. Hemoglobin 11.8 g/dL. Creatinine 0.8 mg/dL.",
        [{"fact_type": "LAB_RESULT", "value": "Hb 11.8 g/dL, Creatinine 0.8 mg/dL", "verbatim": "Hb 11.8 g/dL", "confidence": 0.8}],
    ),
    "07_Pre_Week3_CBC.pdf": (
        "Clinical pathology laboratory. Hemoglobin 7.6 g/dL. Platelets 205 x10^9/L.",
        [{"fact_type": "LAB_RESULT", "value": "Hb 7.6 g/dL (below threshold)", "verbatim": "Hb 7.6 g/dL", "confidence": 0.85}],
    ),
    "08_Repeat_CBC_After_Transfusion.pdf": (
        "Clinical pathology laboratory. Hemoglobin 10.2 g/dL. Platelets 215 x10^9/L.",
        [{"fact_type": "LAB_RESULT", "value": "Hb 10.2 g/dL (recovered)", "verbatim": "Hb 10.2 g/dL", "confidence": 0.85}],
    ),
}


def _install_document_mocks(monkeypatch):
    """Maps each generated scenario PDF's exact bytes to known OCR text + facts, so a real
    upload of a real file drives classify_document (real, keyword-based) and a mocked
    extract_document/extract_clinical_facts (bypassing OCR/LLM) with realistic content."""
    import app.routers.cca as cca_module

    by_hash = {}
    for filename, (text, facts) in _DOC_SPEC.items():
        with open(_doc_path(filename), "rb") as f:
            content = f.read()
        by_hash[hashlib.sha256(content).hexdigest()] = (text, facts)

    def _fake_extract_document(content, content_type):
        text, _facts = by_hash.get(hashlib.sha256(content).hexdigest(), ("", []))
        return {"text": text, "page_count": 1}

    def _fake_extract_clinical_facts(document_text):
        for text, facts in by_hash.values():
            if text == document_text:
                return facts
        return []

    monkeypatch.setattr(cca_module, "extract_document", _fake_extract_document)
    monkeypatch.setattr(cca_module, "extract_clinical_facts", _fake_extract_clinical_facts)


@pytest.fixture
def cervical_org_users(make_user):
    oncologist = make_user(email="onc@cervicalscenario.com", role="CCAMedicalOncologist")
    org_id = oncologist.organization_id
    return {
        "front_desk": make_user(email="frontdesk@cervicalscenario.com", role="CCAFrontDesk", organization_id=org_id),
        "nurse": make_user(email="nurse@cervicalscenario.com", role="CCANurseNavigator", organization_id=org_id),
        "oncologist": oncologist,
        "radiation": make_user(email="rad-onc@cervicalscenario.com", role="CCARadiationOncologist", organization_id=org_id),
        "radiologist": make_user(email="rad@cervicalscenario.com", role="CCARadiologist", organization_id=org_id),
        "pathologist": make_user(email="path@cervicalscenario.com", role="CCAPathologist", organization_id=org_id),
        "lab": make_user(email="lab@cervicalscenario.com", role="CCALabPhlebotomy", organization_id=org_id),
        "coordinator": make_user(email="mdt@cervicalscenario.com", role="CCAMDTCoordinator", organization_id=org_id),
        "external": make_user(email="external@cervicalscenario.com", role="CCAExternalMDTSpecialist", organization_id=org_id),
        "financial": make_user(email="fin@cervicalscenario.com", role="CCAFinancialCounsellor", organization_id=org_id),
        "liaison": make_user(email="liaison@cervicalscenario.com", role="CCAPatientLiaison", organization_id=org_id),
    }


def test_cervical_cancer_full_pipeline(js_page, live_server_url, cervical_org_users, monkeypatch):
    _install_document_mocks(monkeypatch)
    js_page.on("dialog", lambda d: d.accept())
    users = cervical_org_users

    # ---- 1. Front Desk: register patient + upload all source documents ----
    login_as(js_page, live_server_url, users["front_desk"], landing_path="/frontdesk.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate("showTab('registration')")
    js_page.wait_for_timeout(200)
    js_page.evaluate("startNewRegistrationWizard()")
    js_page.wait_for_timeout(400)

    js_page.evaluate("goToWizardStep(1)")
    js_page.fill("#wiz-fullname", "Sunita Deshmukh")
    js_page.fill("#wiz-age", "51")
    js_page.select_option("#wiz-sex", "Female")
    js_page.fill("#wiz-mobile", "+91 90000 40004")

    js_page.evaluate("goToWizardStep(4)")
    for filename in _DOC_SPEC.keys():
        doc_type = "Previous radiology report" if "MRI" in filename or "PET_CT" in filename else (
            "Previous pathology report" if "Pathology" in filename or "HPV" in filename else "Other"
        )
        js_page.select_option("#wiz-doc-type", doc_type)
        js_page.set_input_files("#wiz-doc-file", _doc_path(filename))
        js_page.wait_for_timeout(150)

    js_page.evaluate("goToWizardStep(5)")
    js_page.click('button[onclick="submitFullRegistration()"]')
    js_page.wait_for_timeout(2500)
    assert js_page.js_errors == [], f"registration errors: {js_page.js_errors}"

    from app.main import SessionLocal
    from app.models_cca import CCAPatient

    db = SessionLocal()
    try:
        patient = db.query(CCAPatient).filter(CCAPatient.name == "Sunita Deshmukh").order_by(CCAPatient.id.desc()).first()
        assert patient is not None, "patient was not registered"
        patient_id = patient.id
    finally:
        db.close()

    # ---- 2. Nurse Navigator: intake ----
    login_as(js_page, live_server_url, users["nurse"], landing_path="/nurse_navigator.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate(f"""
        (async () => {{
            const enc = await Api.post(`/cca/patients/{patient_id}/encounters`, {{}});
            window.__nurseEncounterId = enc.encounter.id;
            await Api.post(`/cca/encounters/${{window.__nurseEncounterId}}/intake`, {{
                patient_id: {patient_id},
                chief_complaint: 'Postcoital bleeding for 3 months, cervical biopsy showing malignancy.',
                bp_systolic: 122, bp_diastolic: 78, heart_rate: 80, oxygen_sat: 98,
                ecog: 1, pain_score: 2,
            }});
        }})()
    """)
    js_page.wait_for_timeout(1000)
    assert js_page.js_errors == [], f"nurse intake errors: {js_page.js_errors}"

    # ---- 3. Medical Oncologist: review Patient History, reconcile contradiction, order tests ----
    login_as(js_page, live_server_url, users["oncologist"], landing_path="/medical_oncologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate("showTab('nexus')")
    js_page.wait_for_timeout(1200)
    nexus_html = js_page.inner_html("#nexus-brief-container")
    print("\n\n===== NEXUS BRIEF (cervical) =====\n", nexus_html[:4000], "\n===== END =====\n")

    js_page.evaluate(f"""
        (async () => {{
            await Api.post('/cca/orders', {{ patient_id: {patient_id}, order_type: 'RADIOLOGY', item_name: 'Pelvic MRI + PET-CT Staging', clinical_indication: 'Staging workup for cervical carcinoma.' }});
            await Api.post('/cca/orders', {{ patient_id: {patient_id}, order_type: 'PATHOLOGY', item_name: 'Cervical Biopsy', clinical_indication: 'Tissue diagnosis for cervical mass.' }});
            await Api.post('/cca/orders', {{ patient_id: {patient_id}, order_type: 'LAB', item_name: 'Baseline CBC/Renal Panel', clinical_indication: 'Baseline treatment readiness before chemoradiation.' }});
        }})()
    """)
    js_page.wait_for_timeout(800)
    assert js_page.js_errors == [], f"order raising errors: {js_page.js_errors}"

    from app.models_cca import CCAOrder

    db = SessionLocal()
    try:
        rad_order = db.query(CCAOrder).filter(CCAOrder.patient_id == patient_id, CCAOrder.order_type == "RADIOLOGY").first()
        path_order = db.query(CCAOrder).filter(CCAOrder.patient_id == patient_id, CCAOrder.order_type == "PATHOLOGY").first()
        assert rad_order and path_order
        rad_order_id, path_order_id = rad_order.id, path_order.id
    finally:
        db.close()

    # ---- 4. Radiology finalizes Pelvic MRI + PET-CT ----
    login_as(js_page, live_server_url, users["radiologist"], landing_path="/radiologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate("showTab('imaging')")
    js_page.wait_for_timeout(600)
    js_page.evaluate(f"openImagingOrder({rad_order_id})")
    js_page.wait_for_timeout(400)
    js_page.fill("#img-findings", "Cervical mass 4.5 cm with left parametrial extension. Hypermetabolic left pelvic sidewall lymph nodes. No distant metastatic disease.")
    js_page.fill("#img-impression", "Locally advanced cervical carcinoma, FIGO Stage IIB, with pelvic nodal involvement; no distant metastasis.")
    js_page.click(f'button[onclick="submitImagingReport({rad_order_id})"]')
    js_page.wait_for_timeout(700)
    js_page.click('button:has-text("Finalize Report")')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"radiology finalize errors: {js_page.js_errors}"

    # ---- 5. Pathology finalizes cervical biopsy ----
    login_as(js_page, live_server_url, users["pathologist"], landing_path="/pathologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate("showTab('pathology')")
    js_page.wait_for_timeout(600)
    js_page.evaluate(f"openPathologyOrder({path_order_id})")
    js_page.wait_for_timeout(400)
    js_page.fill("#path-findings", "Squamous cell carcinoma of the cervix, moderately differentiated. HPV-16 positive.")
    js_page.click(f'button[onclick="submitPathologyReport({path_order_id})"]')
    js_page.wait_for_timeout(700)
    js_page.click('button:has-text("Finalize Report")')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"pathology finalize errors: {js_page.js_errors}"

    # ---- 6. Lab collects + results baseline CBC/renal panel ----
    login_as(js_page, live_server_url, users["lab"], landing_path="/laboratory.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate("showTab('lab')")
    js_page.wait_for_timeout(600)

    from app.models_cca import CCAOrder as CCAOrderModel

    db = SessionLocal()
    try:
        lab_order = db.query(CCAOrderModel).filter(CCAOrderModel.patient_id == patient_id, CCAOrderModel.order_type == "LAB").order_by(CCAOrderModel.id.desc()).first()
        lab_order_id = lab_order.id
    finally:
        db.close()

    js_page.click(f'button[onclick="submitLabCollect({lab_order_id})"]')
    js_page.wait_for_timeout(500)
    js_page.evaluate(f"openLabResultInline({lab_order_id})")
    js_page.wait_for_timeout(300)
    js_page.fill(f"#lab-findings-{lab_order_id}", "Hb 11.8 g/dL, Creatinine 0.8 mg/dL.")
    js_page.click(f'button[onclick="submitLabResult({lab_order_id})"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"lab result errors: {js_page.js_errors}"

    # ---- 7. Oncologist: confirm staging (FIGO, not AJCC TNM) ----
    login_as(js_page, live_server_url, users["oncologist"], landing_path="/medical_oncologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate("showTab('staging')")
    js_page.wait_for_timeout(800)
    js_page.fill("#stg-t", "N/A")
    js_page.fill("#stg-n", "N/A")
    js_page.fill("#stg-m", "N/A")
    js_page.fill("#stg-value", "FIGO Stage IIB")
    js_page.fill("#stg-group", "Stage IIB")
    js_page.fill("#stg-reason", "Pelvic MRI and PET-CT confirm FIGO Stage IIB cervical carcinoma with parametrial extension and pelvic nodal involvement, no distant metastasis.")
    js_page.click('button[onclick="submitStagingConfirm()"]')
    js_page.wait_for_timeout(800)
    assert js_page.js_errors == [], f"staging confirm errors: {js_page.js_errors}"

    print("\n\n===== SCENARIO CHECKPOINT: registration through staging complete for patient", patient_id, "=====\n")

    # ---- 8. Oncologist: refer to MDT ----
    js_page.evaluate("showTab('mdt')")
    js_page.wait_for_timeout(600)
    js_page.fill("#mdt-question", "Concurrent chemoradiation strategy for FIGO Stage IIB cervical carcinoma?")
    js_page.click('button[onclick="submitMdtCase()"]')
    js_page.wait_for_timeout(800)
    assert js_page.js_errors == [], f"MDT referral errors: {js_page.js_errors}"

    from app.models_cca import MDTCase

    db = SessionLocal()
    try:
        case = db.query(MDTCase).filter(MDTCase.patient_id == patient_id).order_by(MDTCase.id.desc()).first()
        assert case is not None
        case_id = case.id
    finally:
        db.close()

    # ---- 9. MDT Coordinator: schedule, grant external access ----
    login_as(js_page, live_server_url, users["coordinator"], landing_path="/mdt_coordinator.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate("showTab('mdt')")
    js_page.wait_for_timeout(700)
    js_page.evaluate(f"openMdtCase({case_id}, {patient_id})")
    js_page.wait_for_timeout(500)
    js_page.fill(f"#mdtc-date-{case_id}", "2026-09-14")
    js_page.fill(f"#mdtc-time-{case_id}", "09:30")
    js_page.click(f'button[onclick="submitMdtSchedule({case_id})"]')
    js_page.wait_for_timeout(700)

    js_page.evaluate(f"openMdtCase({case_id}, {patient_id})")
    js_page.wait_for_timeout(500)
    js_page.fill(f"#mdtc-extname-{case_id}", "Dr. Gynae-oncology Second Opinion")
    js_page.select_option(f"#mdtc-extemail-{case_id}", users["external"].email)
    js_page.click(f'button[onclick="submitGrantExternalAccess({case_id})"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"coordinator MDT errors: {js_page.js_errors}"

    # ---- 10. External MDT Specialist: submit opinion ----
    login_as(js_page, live_server_url, users["external"], landing_path="/external_mdt_specialist.html")
    js_page.wait_for_timeout(600)
    js_page.click(f'button[onclick="loadOpinionsAndForm({case_id})"]')
    js_page.wait_for_timeout(400)
    js_page.fill(f"#opinion-rec-{case_id}", "Agree with definitive concurrent chemoradiation; surgery not indicated for this parametrial extension.")
    js_page.fill(f"#opinion-rationale-{case_id}", "Parametrial involvement makes this a chemoradiation, not surgical, case per standard practice.")
    js_page.select_option(f"#opinion-certainty-{case_id}", "High")
    js_page.click(f'button[onclick="submitOpinion({case_id})"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"external specialist errors: {js_page.js_errors}"

    # ---- 11. Oncologist: record recommendation, Coordinator: disposition (Accept) ----
    login_as(js_page, live_server_url, users["oncologist"], landing_path="/medical_oncologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate("showTab('mdt')")
    js_page.wait_for_timeout(600)
    js_page.click(f'button[onclick="openRecommendationForm({case_id})"]')
    js_page.wait_for_timeout(300)
    js_page.fill(f"#mdt-rec-text-{case_id}", "Proceed with definitive concurrent chemoradiation: external beam radiation with weekly cisplatin, followed by brachytherapy.")
    js_page.click(f'button[onclick="submitMdtRecommendation({case_id})"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"MDT recommendation errors: {js_page.js_errors}"

    login_as(js_page, live_server_url, users["coordinator"], landing_path="/mdt_coordinator.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate("showTab('mdt')")
    js_page.wait_for_timeout(700)
    js_page.evaluate(f"openMdtCase({case_id}, {patient_id})")
    js_page.wait_for_timeout(500)
    js_page.click(f'button[onclick="submitMdtCoordinatorDisposition({case_id}, \'ACCEPT\')"]')
    js_page.wait_for_timeout(800)
    assert js_page.js_errors == [], f"coordinator disposition errors: {js_page.js_errors}"

    # ---- 12. Radiation Oncologist: create + sign Radiation Therapy Treatment Plan ----
    login_as(js_page, live_server_url, users["radiation"], landing_path="/radiation_oncologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate("showTab('treatmentplan')")
    js_page.wait_for_timeout(700)
    js_page.fill("#tp-modality", "Radiation Therapy")
    js_page.fill("#tp-protocol", "External beam radiation 45 Gy/25 fractions + brachytherapy boost, concurrent weekly cisplatin")
    js_page.fill("#tp-sessions", "25")
    js_page.click('button[onclick="submitCreateTreatmentPlan()"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"create radiation treatment plan errors: {js_page.js_errors}"

    js_page.click('button[onclick="signTreatmentPlanSubmit()"]')
    js_page.wait_for_timeout(800)
    assert js_page.js_errors == [], f"sign radiation treatment plan errors: {js_page.js_errors}"

    from app.models_cca import TreatmentPlan

    db = SessionLocal()
    try:
        rt_plan = db.query(TreatmentPlan).filter(TreatmentPlan.patient_id == patient_id, TreatmentPlan.modality == "Radiation Therapy").order_by(TreatmentPlan.id.desc()).first()
        assert rt_plan is not None and rt_plan.status == "ACTIVE"
        rt_plan_id = rt_plan.id
    finally:
        db.close()

    # ---- 13. Medical Oncologist: create + sign concurrent Systemic Therapy Treatment Plan (weekly cisplatin) ----
    login_as(js_page, live_server_url, users["oncologist"], landing_path="/medical_oncologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate("showTab('treatmentplan')")
    js_page.wait_for_timeout(700)
    js_page.fill("#tp-protocol", "Weekly Cisplatin (concurrent with radiation)")
    js_page.fill("#tp-sessions", "5")
    js_page.click('button[onclick="submitCreateTreatmentPlan()"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"create systemic treatment plan errors: {js_page.js_errors}"

    js_page.click('button[onclick="signTreatmentPlanSubmit()"]')
    js_page.wait_for_timeout(800)
    assert js_page.js_errors == [], f"sign systemic treatment plan errors: {js_page.js_errors}"

    db = SessionLocal()
    try:
        sys_plan = db.query(TreatmentPlan).filter(TreatmentPlan.patient_id == patient_id, TreatmentPlan.modality != "Radiation Therapy").order_by(TreatmentPlan.id.desc()).first()
        assert sys_plan is not None and sys_plan.status == "ACTIVE"
        sys_plan_id = sys_plan.id
    finally:
        db.close()

    # ---- 14. Week 1 cisplatin: create + sign Treatment Order, clear standard dose ----
    js_page.evaluate("loadTreatmentPlanView()")
    js_page.wait_for_timeout(600)
    js_page.click(f'button[onclick="submitCreateTreatmentOrder({sys_plan_id})"]')
    js_page.wait_for_timeout(700)
    html = js_page.inner_html("#treatmentplan-content")
    order_id = int(re.search(r"submitSignTreatmentOrder\((\d+)\)", html).group(1))
    js_page.click(f'button[onclick="submitSignTreatmentOrder({order_id})"]')
    js_page.wait_for_timeout(700)
    js_page.select_option("#clearance-decision-onc", "CLEARED")
    js_page.fill("#clearance-reason-onc", "Baseline Hb/renal function within tolerance; standard dose week 1 cisplatin.")
    js_page.click(f'button[onclick="submitClearanceOnc({order_id})"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"week 1 clearance errors: {js_page.js_errors}"

    # ---- 15. Oncologist orders pre-week-3 CBC; Lab posts anemia; oncologist HOLDs ----
    js_page.evaluate(f"""
        (async () => {{
            await Api.post('/cca/orders', {{ patient_id: {patient_id}, order_type: 'LAB', item_name: 'Pre-Week 3 CBC', clinical_indication: 'Pre-cisplatin week 3 count check.' }});
        }})()
    """)
    js_page.wait_for_timeout(500)

    login_as(js_page, live_server_url, users["lab"], landing_path="/laboratory.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate("showTab('lab')")
    js_page.wait_for_timeout(600)

    from app.models_cca import CCAOrder as CCAOrderModel2

    db = SessionLocal()
    try:
        cbc_order = db.query(CCAOrderModel2).filter(CCAOrderModel2.patient_id == patient_id, CCAOrderModel2.item_name == "Pre-Week 3 CBC").first()
        cbc_order_id = cbc_order.id
    finally:
        db.close()

    js_page.evaluate("loadLabWorklist()")
    js_page.wait_for_timeout(500)
    js_page.click(f'button[onclick="submitLabCollect({cbc_order_id})"]')
    js_page.wait_for_timeout(500)
    js_page.evaluate(f"openLabResultInline({cbc_order_id})")
    js_page.wait_for_timeout(300)
    js_page.fill(f"#lab-findings-{cbc_order_id}", "Hemoglobin 7.6 g/dL -- below institutional threshold for weekly cisplatin. Platelets 205 x10^9/L.")
    js_page.check(f"#lab-critical-{cbc_order_id}")
    js_page.click(f'button[onclick="submitLabResult({cbc_order_id})"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"pre-week-3 lab errors: {js_page.js_errors}"

    login_as(js_page, live_server_url, users["oncologist"], landing_path="/medical_oncologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate("showTab('treatmentplan')")
    js_page.wait_for_timeout(700)
    html = js_page.inner_html("#treatmentplan-content")
    assert "Create Treatment Order" in html, f"expected a fresh order slot for week 3:\n{html[:2000]}"
    js_page.click(f'button[onclick="submitCreateTreatmentOrder({sys_plan_id})"]')
    js_page.wait_for_timeout(700)
    html = js_page.inner_html("#treatmentplan-content")
    week3_order_id = int(re.search(r"submitSignTreatmentOrder\((\d+)\)", html).group(1))
    js_page.click(f'button[onclick="submitSignTreatmentOrder({week3_order_id})"]')
    js_page.wait_for_timeout(700)
    js_page.select_option("#clearance-decision-onc", "HELD")
    js_page.fill("#clearance-reason-onc", "Hemoglobin 7.6 g/dL -- below threshold for weekly cisplatin. Holding, transfusion and repeat CBC arranged.")
    js_page.click(f'button[onclick="submitClearanceOnc({week3_order_id})"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"week 3 hold errors: {js_page.js_errors}"

    from app.models_cca import TreatmentSession

    db = SessionLocal()
    try:
        session = db.query(TreatmentSession).filter(TreatmentSession.treatment_plan_id == sys_plan_id).order_by(TreatmentSession.id.desc()).first()
        assert session.status == "HELD"
    finally:
        db.close()

    # ---- 16. Repeat CBC recovers after transfusion; oncologist clears week 3 ----
    login_as(js_page, live_server_url, users["oncologist"], landing_path="/medical_oncologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate(f"""
        (async () => {{
            await Api.post('/cca/orders', {{ patient_id: {patient_id}, order_type: 'LAB', item_name: 'Repeat CBC After Transfusion', clinical_indication: 'Reassessment after anemia hold and transfusion.' }});
        }})()
    """)
    js_page.wait_for_timeout(500)

    login_as(js_page, live_server_url, users["lab"], landing_path="/laboratory.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate("showTab('lab')")
    js_page.wait_for_timeout(600)

    db = SessionLocal()
    try:
        repeat_order = db.query(CCAOrderModel2).filter(CCAOrderModel2.patient_id == patient_id, CCAOrderModel2.item_name == "Repeat CBC After Transfusion").first()
        repeat_order_id = repeat_order.id
    finally:
        db.close()

    js_page.evaluate("loadLabWorklist()")
    js_page.wait_for_timeout(500)
    js_page.click(f'button[onclick="submitLabCollect({repeat_order_id})"]')
    js_page.wait_for_timeout(500)
    js_page.evaluate(f"openLabResultInline({repeat_order_id})")
    js_page.wait_for_timeout(300)
    js_page.fill(f"#lab-findings-{repeat_order_id}", "Hemoglobin 10.2 g/dL after transfusion -- recovered. Platelets 215 x10^9/L.")
    js_page.click(f'button[onclick="submitLabResult({repeat_order_id})"]')
    js_page.wait_for_timeout(700)

    login_as(js_page, live_server_url, users["oncologist"], landing_path="/medical_oncologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate("showTab('treatmentplan')")
    js_page.wait_for_timeout(700)
    html = js_page.inner_html("#treatmentplan-content")
    assert "Decide Treatment Clearance" in html, f"expected the still-signed order's clearance form after HELD:\n{html[:2000]}"
    js_page.select_option("#clearance-decision-onc", "CLEARED")
    js_page.fill("#clearance-reason-onc", "Hemoglobin recovered to 10.2 g/dL after transfusion. Cleared for week 3 cisplatin.")
    js_page.click(f'button[onclick="submitClearanceOnc({week3_order_id})"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"week 3 clearance-after-recovery errors: {js_page.js_errors}"

    from app.models_cca import TreatmentOrder

    db = SessionLocal()
    try:
        db_order = db.query(TreatmentOrder).filter(TreatmentOrder.id == week3_order_id).first()
        assert db_order.status == "EXECUTED"
    finally:
        db.close()

    # ---- 17. Oncologist: create Care Plan from BOTH Treatment Plans (Radiation + Systemic) ----
    js_page.evaluate("showTab('careplan')")
    js_page.wait_for_timeout(700)
    cp_html = js_page.inner_html("#careplan-content")
    assert "Create Care Plan" in cp_html, f"no create-care-plan form:\n{cp_html[:2000]}"
    # Both signed plans should be offered as source plans -- confirms a Care Plan can be built
    # across modalities, not just from whichever single plan the current role happens to own.
    assert "Radiation Therapy" in cp_html and "Weekly Cisplatin" in cp_html, f"expected both plans listed as sources:\n{cp_html[:3000]}"
    js_page.fill("#cp-create-systemic", "Weekly cisplatin concurrent with radiation, 5 planned doses.")
    js_page.fill("#cp-create-radiation", "External beam radiation 45 Gy/25 fractions + brachytherapy boost.")
    js_page.click('button[onclick="submitCreateCarePlan()"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"care plan creation errors: {js_page.js_errors}"

    from app.models_cca import CarePlan

    db = SessionLocal()
    try:
        cp = db.query(CarePlan).filter(CarePlan.patient_id == patient_id).first()
        assert cp is not None and cp.status == "ACTIVE"
        assert set(cp.source_treatment_plan_ids or []) == {rt_plan_id, sys_plan_id}
    finally:
        db.close()

    # ---- 18. Financial Counsellor ----
    login_as(js_page, live_server_url, users["financial"], landing_path="/patient_financial_services.html")
    js_page.wait_for_timeout(600)
    assert js_page.js_errors == [], f"financial counsellor load errors: {js_page.js_errors}"

    # ---- 19. Patient Liaison ----
    login_as(js_page, live_server_url, users["liaison"], landing_path="/patient_liaison.html")
    js_page.wait_for_timeout(600)
    js_page.evaluate("showTab('coordination')")
    js_page.wait_for_timeout(600)
    assert js_page.js_errors == [], f"patient liaison load errors: {js_page.js_errors}"

    # ---- 20. Patient History cross-role visibility ----
    login_as(js_page, live_server_url, users["coordinator"], landing_path="/mdt_coordinator.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate("showTab('history')")
    js_page.wait_for_timeout(1000)
    final_history_html = js_page.inner_html("#history-content")
    assert "Investigations Ordered" in final_history_html
    assert "Repeat CBC After Transfusion" in final_history_html or "Pre-Week 3 CBC" in final_history_html
    assert js_page.js_errors == [], f"final patient history errors: {js_page.js_errors}"

    # ---- 21. Negative permission checks ----
    import requests
    from tests.e2e.conftest import mint_tokens

    fd_tokens = mint_tokens(users["front_desk"])
    resp = requests.get(
        f"{live_server_url}/api/cca/patients/{patient_id}/case-summary",
        headers={"Authorization": f"Bearer {fd_tokens['access_token']}"},
    )
    assert resp.status_code == 403, f"Front Desk should not access clinical case-summary, got {resp.status_code}"

    ext_tokens = mint_tokens(users["external"])
    resp2 = requests.get(
        f"{live_server_url}/api/cca/patients",
        headers={"Authorization": f"Bearer {ext_tokens['access_token']}"},
    )
    assert resp2.status_code == 403, f"External MDT Specialist should not browse the patient list, got {resp2.status_code}: {resp2.text[:300]}"

    print("\n\n===== CERVICAL SCENARIO: FULL PIPELINE PASSED for patient", patient_id, "=====\n")
