"""
Full-pipeline scenario test: NSCLC (lung cancer), EGFR-mutant, right upper lobe -- exercising
a genuinely different disease site/staging system/specialist mix than the breast-cancer demo
case this app was originally built and tested against. Drives the real running app through a
real browser across the full role pipeline: Front Desk registration + document upload ->
Nurse Navigator intake -> Medical Oncologist review/orders -> Radiology/Pathology/Lab finalize
-> Staging (with the deliberate laterality contradiction NEXUS must flag) -> MDT (referral,
Coordinator schedule + external access, External MDT Specialist opinion, oncologist
recommendation, Coordinator disposition) -> Treatment Plan -> Treatment Order + Clearance
(Cycle 1) -> Lab posts an abnormal renal panel -> oncologist holds -> repeat labs clear ->
Cycle 2 -> Care Plan -> Financial Counsellor -> Patient Liaison -> Patient History cross-role
visibility -> negative-permission checks.

Source documents: data/scenarios/lung/*.pdf (generated by tools/generate_scenario_docs.py).
OCR (extract_document) and LLM fact extraction (extract_clinical_facts) are mocked -- see
module docstring precedent in tests/integration/test_patient_document_ocr.py and this
session's tests/conftest.py::_no_live_groq_calls -- keyed by each file's exact bytes so a real
upload of a real generated PDF still drives realistic classification/fact extraction without
a live OCR model or LLM call.
"""
import hashlib
import os

import pytest

from tests.e2e.conftest import login_as

pytestmark = pytest.mark.e2e

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DOC_DIR = os.path.join(REPO_ROOT, "data", "scenarios", "lung")


def _doc_path(filename):
    return os.path.join(DOC_DIR, filename)


# filename -> (ocr_text, facts) -- facts use the exact shape extract_clinical_facts returns.
_DOC_SPEC = {
    "01_Referral_Letter.pdf": (
        "Referral letter. Please evaluate the left lung mass and advise oncology management.",
        [{"fact_type": "LATERALITY", "value": "Left", "verbatim": "left lung mass", "confidence": 0.7}],
    ),
    "02_Outside_CT_Chest_Summary.pdf": (
        "Computed tomography chest. Impression: spiculated mass right upper lobe, right hilar lymphadenopathy.",
        [{"fact_type": "LATERALITY", "value": "Right", "verbatim": "right upper lobe", "confidence": 0.9},
         {"fact_type": "PRIMARY_SITE", "value": "Right upper lobe lung", "verbatim": "right upper lobe mass", "confidence": 0.9}],
    ),
    "03_Bronchoscopy_Biopsy_Pathology.pdf": (
        "Surgical pathology biopsy report. Histopathology: adenocarcinoma, moderately differentiated. Right upper lobe.",
        [{"fact_type": "HISTOLOGY", "value": "Adenocarcinoma", "verbatim": "adenocarcinoma", "confidence": 0.95},
         {"fact_type": "LATERALITY", "value": "Right", "verbatim": "right upper lobe", "confidence": 0.9}],
    ),
    "04_Molecular_Biomarker_Report.pdf": (
        "Immunohistochemistry and biomarker report. EGFR exon 19 deletion positive. ALK negative. PD-L1 TPS 40%.",
        [{"fact_type": "BIOMARKER_RESULT", "value": "EGFR exon 19 deletion positive", "verbatim": "EGFR exon 19 deletion detected", "confidence": 0.9}],
    ),
    "05_Baseline_Laboratory_Report.pdf": (
        "Clinical pathology laboratory. Hemoglobin 13.8 g/dL. Leukocyte count normal. Creatinine 0.9 mg/dL.",
        [{"fact_type": "LAB_RESULT", "value": "Hb 13.8 g/dL, Creatinine 0.9 mg/dL", "verbatim": "Hb 13.8 g/dL", "confidence": 0.8}],
    ),
    "06_PET_CT_Staging_Report.pdf": (
        "Radiodiagnosis PET-CT. Impression: cT2bN1M0 right upper lobe non-small cell lung carcinoma.",
        [{"fact_type": "T_EVIDENCE", "value": "cT2b", "verbatim": "cT2bN1M0", "confidence": 0.85},
         {"fact_type": "N_EVIDENCE", "value": "cN1", "verbatim": "cT2bN1M0", "confidence": 0.85},
         {"fact_type": "M_EVIDENCE", "value": "cM0", "verbatim": "cT2bN1M0", "confidence": 0.85}],
    ),
    "07_Pre_Cycle2_Renal_Panel.pdf": (
        "Clinical pathology laboratory. Creatinine 2.1 mg/dL. eGFR approximately 32.",
        [{"fact_type": "LAB_RESULT", "value": "Creatinine 2.1 mg/dL (elevated)", "verbatim": "Creatinine 2.1 mg/dL", "confidence": 0.85}],
    ),
    "08_Repeat_Renal_Panel_After_Delay.pdf": (
        "Clinical pathology laboratory. Creatinine 1.0 mg/dL. eGFR approximately 68.",
        [{"fact_type": "LAB_RESULT", "value": "Creatinine 1.0 mg/dL (recovered)", "verbatim": "Creatinine 1.0 mg/dL", "confidence": 0.85}],
    ),
}


def _install_document_mocks(monkeypatch):
    """Maps each generated scenario PDF's exact bytes to known OCR text + facts, so a real
    upload of a real file drives classify_document (real, keyword-based) and a mocked
    extract_document/extract_clinical_facts (bypassing OCR/LLM) with realistic content."""
    import app.routers.cca as cca_module

    by_hash = {}
    for filename, (text, facts) in _DOC_SPEC.items():
        with open(_doc_path(filename), "rb") as f:
            content = f.read()
        by_hash[hashlib.sha256(content).hexdigest()] = (text, facts)

    def _fake_extract_document(content, content_type):
        text, _facts = by_hash.get(hashlib.sha256(content).hexdigest(), ("", []))
        return {"text": text, "page_count": 1}

    def _fake_extract_clinical_facts(document_text):
        for text, facts in by_hash.values():
            if text == document_text:
                return facts
        return []

    monkeypatch.setattr(cca_module, "extract_document", _fake_extract_document)
    monkeypatch.setattr(cca_module, "extract_clinical_facts", _fake_extract_clinical_facts)


@pytest.fixture
def lung_org_users(make_user):
    oncologist = make_user(email="onc@lungscenario.com", role="CCAMedicalOncologist")
    org_id = oncologist.organization_id
    return {
        "front_desk": make_user(email="frontdesk@lungscenario.com", role="CCAFrontDesk", organization_id=org_id),
        "nurse": make_user(email="nurse@lungscenario.com", role="CCANurseNavigator", organization_id=org_id),
        "oncologist": oncologist,
        "radiologist": make_user(email="rad@lungscenario.com", role="CCARadiologist", organization_id=org_id),
        "pathologist": make_user(email="path@lungscenario.com", role="CCAPathologist", organization_id=org_id),
        "lab": make_user(email="lab@lungscenario.com", role="CCALabPhlebotomy", organization_id=org_id),
        "coordinator": make_user(email="mdt@lungscenario.com", role="CCAMDTCoordinator", organization_id=org_id),
        "external": make_user(email="external@lungscenario.com", role="CCAExternalMDTSpecialist", organization_id=org_id),
        "financial": make_user(email="fin@lungscenario.com", role="CCAFinancialCounsellor", organization_id=org_id),
        "liaison": make_user(email="liaison@lungscenario.com", role="CCAPatientLiaison", organization_id=org_id),
    }


def test_lung_cancer_full_pipeline(js_page, live_server_url, lung_org_users, monkeypatch):
    _install_document_mocks(monkeypatch)
    js_page.on("dialog", lambda d: d.accept())
    users = lung_org_users

    # ---- 1. Front Desk: register patient + upload all source documents ----
    login_as(js_page, live_server_url, users["front_desk"], landing_path="/frontdesk.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate("showTab('registration')")
    js_page.wait_for_timeout(200)
    js_page.evaluate("startNewRegistrationWizard()")
    js_page.wait_for_timeout(400)

    js_page.evaluate("goToWizardStep(1)")
    js_page.fill("#wiz-fullname", "Arjun Verma")
    js_page.fill("#wiz-age", "58")
    js_page.select_option("#wiz-sex", "Male")
    js_page.fill("#wiz-mobile", "+91 90000 20002")

    js_page.evaluate("goToWizardStep(4)")
    for filename in _DOC_SPEC.keys():
        doc_type = "Previous radiology report" if "CT" in filename or "PET" in filename else (
            "Previous pathology report" if "Pathology" in filename or "Biopsy" in filename or "Biomarker" in filename else "Other"
        )
        js_page.select_option("#wiz-doc-type", doc_type)
        js_page.set_input_files("#wiz-doc-file", _doc_path(filename))
        js_page.wait_for_timeout(150)

    js_page.evaluate("goToWizardStep(5)")
    js_page.click('button[onclick="submitFullRegistration()"]')
    js_page.wait_for_timeout(2500)
    assert js_page.js_errors == [], f"registration errors: {js_page.js_errors}"

    from app.main import SessionLocal
    from app.models_cca import CCAPatient

    db = SessionLocal()
    try:
        patient = db.query(CCAPatient).filter(CCAPatient.mrn.isnot(None), CCAPatient.name == "Arjun Verma").order_by(CCAPatient.id.desc()).first()
        assert patient is not None, "patient was not registered"
        patient_id = patient.id
    finally:
        db.close()

    # ---- 2. Nurse Navigator: intake ----
    login_as(js_page, live_server_url, users["nurse"], landing_path="/nurse_navigator.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"openPatientFromQueue({patient_id})" if False else f"currentPatientId = {patient_id}")
    # nurse_navigator.html opens intake via its own queue card; drive the encounter/intake
    # endpoints directly through the already-open page's Api helper for determinism, since the
    # 6-step wizard's exact opening trigger varies by queue-card content we don't control here.
    js_page.evaluate(f"""
        (async () => {{
            const enc = await Api.post(`/cca/patients/{patient_id}/encounters`, {{}});
            window.__nurseEncounterId = enc.encounter.id;
            await Api.post(`/cca/encounters/${{window.__nurseEncounterId}}/intake`, {{
                patient_id: {patient_id},
                chief_complaint: 'Persistent cough with hemoptysis, right upper lobe mass on outside CT.',
                bp_systolic: 124, bp_diastolic: 80, heart_rate: 76, oxygen_sat: 97,
                ecog: 0, pain_score: 1,
            }});
        }})()
    """)
    js_page.wait_for_timeout(1000)
    assert js_page.js_errors == [], f"nurse intake errors: {js_page.js_errors}"

    # ---- 3. Medical Oncologist: review Patient History, reconcile contradiction, order tests ----
    login_as(js_page, live_server_url, users["oncologist"], landing_path="/medical_oncologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate("showTab('history')")
    js_page.wait_for_timeout(800)
    history_html = js_page.inner_html("#history-content")
    print("\n\n===== PATIENT HISTORY (contradiction check) =====\n", history_html[:3000], "\n===== END =====\n")

    # NEXUS contradiction: laterality conflict must be visible somewhere in the clinical
    # decision surface. Check the NEXUS clinical brief / AI Search rather than assuming a
    # specific screen, since contradiction display is NEXUS's responsibility, not History's.
    js_page.evaluate("showTab('nexus')")
    js_page.wait_for_timeout(1200)
    nexus_html = js_page.inner_html("#nexus-brief-container")
    print("\n\n===== NEXUS BRIEF =====\n", nexus_html[:4000], "\n===== END =====\n")

    # Raise imaging/pathology orders directly (the manual "Raise Order" UI field only exposes
    # LAB in its dropdown; RADIOLOGY/PATHOLOGY orders are otherwise only reachable via
    # AI-Scribe-detected labTests, which would require mocking a second Groq call shape here).
    js_page.evaluate(f"""
        (async () => {{
            await Api.post('/cca/orders', {{ patient_id: {patient_id}, order_type: 'RADIOLOGY', item_name: 'PET-CT Staging', clinical_indication: 'Staging workup for right upper lobe mass.' }});
            await Api.post('/cca/orders', {{ patient_id: {patient_id}, order_type: 'PATHOLOGY', item_name: 'Bronchoscopy Biopsy', clinical_indication: 'Tissue diagnosis for right upper lobe mass.' }});
            await Api.post('/cca/orders', {{ patient_id: {patient_id}, order_type: 'LAB', item_name: 'Baseline CBC/Renal Panel', clinical_indication: 'Baseline treatment readiness.' }});
        }})()
    """)
    js_page.wait_for_timeout(800)
    assert js_page.js_errors == [], f"order raising errors: {js_page.js_errors}"

    from app.models_cca import CCAOrder

    db = SessionLocal()
    try:
        rad_order = db.query(CCAOrder).filter(CCAOrder.patient_id == patient_id, CCAOrder.order_type == "RADIOLOGY").first()
        path_order = db.query(CCAOrder).filter(CCAOrder.patient_id == patient_id, CCAOrder.order_type == "PATHOLOGY").first()
        assert rad_order and path_order
        rad_order_id, path_order_id = rad_order.id, path_order.id
    finally:
        db.close()

    # ---- 4. Radiology finalizes PET-CT ----
    login_as(js_page, live_server_url, users["radiologist"], landing_path="/radiologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate("showTab('imaging')")
    js_page.wait_for_timeout(600)
    js_page.evaluate(f"openImagingOrder({rad_order_id})")
    js_page.wait_for_timeout(400)
    js_page.fill("#img-findings", "Hypermetabolic right upper lobe mass with right hilar nodal uptake. No distant hypermetabolic disease.")
    js_page.fill("#img-impression", "Findings consistent with cT2bN1M0 right upper lobe non-small cell lung carcinoma; no distant metastasis.")
    js_page.click(f'button[onclick="submitImagingReport({rad_order_id})"]')
    js_page.wait_for_timeout(700)
    js_page.click('button:has-text("Finalize Report")')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"radiology finalize errors: {js_page.js_errors}"

    # ---- 5. Pathology finalizes bronchoscopy biopsy ----
    login_as(js_page, live_server_url, users["pathologist"], landing_path="/pathologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate("showTab('pathology')")
    js_page.wait_for_timeout(600)
    js_page.evaluate(f"openPathologyOrder({path_order_id})")
    js_page.wait_for_timeout(400)
    js_page.fill("#path-findings", "Adenocarcinoma, moderately differentiated, right upper lobe. EGFR exon 19 deletion positive, ALK negative, PD-L1 TPS 40%.")
    js_page.click(f'button[onclick="submitPathologyReport({path_order_id})"]')
    js_page.wait_for_timeout(700)
    js_page.click('button:has-text("Finalize Report")')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"pathology finalize errors: {js_page.js_errors}"

    # ---- 6. Lab collects + results baseline CBC/renal panel ----
    login_as(js_page, live_server_url, users["lab"], landing_path="/laboratory.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate("showTab('lab')")
    js_page.wait_for_timeout(600)

    from app.models_cca import CCAOrder as CCAOrderModel
    db = SessionLocal()
    try:
        lab_order = db.query(CCAOrderModel).filter(CCAOrderModel.patient_id == patient_id, CCAOrderModel.order_type == "LAB").order_by(CCAOrderModel.id.desc()).first()
        lab_order_id = lab_order.id
    finally:
        db.close()

    js_page.click(f'button[onclick="submitLabCollect({lab_order_id})"]')
    js_page.wait_for_timeout(500)
    js_page.evaluate(f"openLabResultInline({lab_order_id})")
    js_page.wait_for_timeout(300)
    js_page.fill(f"#lab-findings-{lab_order_id}", "Hb 13.8 g/dL, ANC 4.1 x10^9/L, Platelets 245 x10^9/L, Creatinine 0.9 mg/dL.")
    js_page.click(f'button[onclick="submitLabResult({lab_order_id})"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"lab result errors: {js_page.js_errors}"

    # ---- 7. Oncologist: confirm staging ----
    login_as(js_page, live_server_url, users["oncologist"], landing_path="/medical_oncologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate("showTab('staging')")
    js_page.wait_for_timeout(800)
    js_page.fill("#stg-t", "cT2b")
    js_page.fill("#stg-n", "cN1")
    js_page.fill("#stg-m", "cM0")
    js_page.fill("#stg-value", "cT2b cN1 cM0")
    js_page.fill("#stg-group", "Stage IIB")
    js_page.fill("#stg-reason", "PET-CT and bronchoscopy biopsy confirm right upper lobe NSCLC with right hilar nodal involvement, no distant metastasis.")
    js_page.click('button[onclick="submitStagingConfirm()"]')
    js_page.wait_for_timeout(800)
    assert js_page.js_errors == [], f"staging confirm errors: {js_page.js_errors}"

    print("\n\n===== SCENARIO CHECKPOINT: registration through staging complete for patient", patient_id, "=====\n")

    # ---- 8. Oncologist: refer to MDT ----
    js_page.evaluate("showTab('mdt')")
    js_page.wait_for_timeout(600)
    js_page.fill("#mdt-question", "Optimal sequencing: upfront resection vs neoadjuvant chemotherapy for this EGFR-mutant right upper lobe NSCLC?")
    js_page.click('button[onclick="submitMdtCase()"]')
    js_page.wait_for_timeout(800)
    assert js_page.js_errors == [], f"MDT referral errors: {js_page.js_errors}"

    from app.models_cca import MDTCase

    db = SessionLocal()
    try:
        case = db.query(MDTCase).filter(MDTCase.patient_id == patient_id).order_by(MDTCase.id.desc()).first()
        assert case is not None
        case_id = case.id
    finally:
        db.close()

    # ---- 9. MDT Coordinator: schedule, invite participant, grant external access ----
    login_as(js_page, live_server_url, users["coordinator"], landing_path="/mdt_coordinator.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate("showTab('mdt')")
    js_page.wait_for_timeout(700)
    js_page.evaluate(f"openMdtCase({case_id}, {patient_id})")
    js_page.wait_for_timeout(500)
    js_page.fill(f"#mdtc-date-{case_id}", "2026-09-15")
    js_page.fill(f"#mdtc-time-{case_id}", "11:00")
    js_page.click(f'button[onclick="submitMdtSchedule({case_id})"]')
    js_page.wait_for_timeout(700)

    js_page.evaluate(f"openMdtCase({case_id}, {patient_id})")
    js_page.wait_for_timeout(500)
    js_page.fill(f"#mdtc-extname-{case_id}", "Dr. Thoracic Second Opinion")
    js_page.fill(f"#mdtc-extemail-{case_id}", users["external"].email)
    js_page.click(f'button[onclick="submitGrantExternalAccess({case_id})"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"coordinator MDT errors: {js_page.js_errors}"

    # ---- 10. External MDT Specialist: submit opinion ----
    login_as(js_page, live_server_url, users["external"], landing_path="/external_mdt_specialist.html")
    js_page.wait_for_timeout(600)
    js_page.click(f'button[onclick="loadOpinionsAndForm({case_id})"]')
    js_page.wait_for_timeout(400)
    js_page.fill(f"#opinion-rec-{case_id}", "Favor neoadjuvant chemotherapy given nodal involvement, then reassess for resection.")
    js_page.fill(f"#opinion-rationale-{case_id}", "Nodal downstaging improves resection margins in N1 disease.")
    js_page.select_option(f"#opinion-certainty-{case_id}", "Moderate")
    js_page.click(f'button[onclick="submitOpinion({case_id})"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"external specialist errors: {js_page.js_errors}"

    # ---- 11. Oncologist: record recommendation, Coordinator: disposition (Accept) ----
    login_as(js_page, live_server_url, users["oncologist"], landing_path="/medical_oncologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate("showTab('mdt')")
    js_page.wait_for_timeout(600)
    js_page.click(f'button[onclick="openRecommendationForm({case_id})"]')
    js_page.wait_for_timeout(300)
    js_page.fill(f"#mdt-rec-text-{case_id}", "Proceed with neoadjuvant carboplatin/pemetrexed chemotherapy, reassess for right upper lobectomy after response.")
    js_page.click(f'button[onclick="submitMdtRecommendation({case_id})"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"MDT recommendation errors: {js_page.js_errors}"

    login_as(js_page, live_server_url, users["coordinator"], landing_path="/mdt_coordinator.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate("showTab('mdt')")
    js_page.wait_for_timeout(700)
    js_page.evaluate(f"openMdtCase({case_id}, {patient_id})")
    js_page.wait_for_timeout(500)
    js_page.click(f'button[onclick="submitMdtCoordinatorDisposition({case_id}, \'ACCEPT\')"]')
    js_page.wait_for_timeout(800)
    assert js_page.js_errors == [], f"coordinator disposition errors: {js_page.js_errors}"

    # ---- 12. Oncologist: create + sign Treatment Plan ----
    login_as(js_page, live_server_url, users["oncologist"], landing_path="/medical_oncologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate("showTab('treatmentplan')")
    js_page.wait_for_timeout(700)
    js_page.fill("#tp-protocol", "Carboplatin + Pemetrexed, neoadjuvant")
    js_page.fill("#tp-sessions", "4")
    js_page.click('button[onclick="submitCreateTreatmentPlan()"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"create treatment plan errors: {js_page.js_errors}"

    js_page.click('button[onclick="signTreatmentPlanSubmit()"]')
    js_page.wait_for_timeout(800)
    assert js_page.js_errors == [], f"sign treatment plan errors: {js_page.js_errors}"

    from app.models_cca import TreatmentPlan

    db = SessionLocal()
    try:
        plan = db.query(TreatmentPlan).filter(TreatmentPlan.patient_id == patient_id).order_by(TreatmentPlan.id.desc()).first()
        assert plan.status == "ACTIVE"
        plan_id = plan.id
    finally:
        db.close()

    # ---- 13. Cycle 1: create + sign Treatment Order, clear standard dose ----
    js_page.evaluate("loadTreatmentPlanView()")
    js_page.wait_for_timeout(600)
    js_page.click(f'button[onclick="submitCreateTreatmentOrder({plan_id})"]')
    js_page.wait_for_timeout(700)
    html = js_page.inner_html("#treatmentplan-content")
    import re
    order_id = int(re.search(r"submitSignTreatmentOrder\((\d+)\)", html).group(1))
    js_page.click(f'button[onclick="submitSignTreatmentOrder({order_id})"]')
    js_page.wait_for_timeout(700)
    js_page.select_option("#clearance-decision-onc", "CLEARED")
    js_page.fill("#clearance-reason-onc", "Baseline labs within tolerance; standard dose cycle 1.")
    js_page.click(f'button[onclick="submitClearanceOnc({order_id})"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"cycle 1 clearance errors: {js_page.js_errors}"

    # ---- 14. Oncologist orders pre-cycle-2 labs; Lab posts abnormal result; oncologist HOLDs ----
    js_page.evaluate(f"""
        (async () => {{
            await Api.post('/cca/orders', {{ patient_id: {patient_id}, order_type: 'LAB', item_name: 'Pre-Cycle 2 Renal Panel', clinical_indication: 'Pre-chemotherapy renal function check.' }});
        }})()
    """)
    js_page.wait_for_timeout(500)

    login_as(js_page, live_server_url, users["lab"], landing_path="/laboratory.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate("showTab('lab')")
    js_page.wait_for_timeout(600)

    from app.models_cca import CCAOrder as CCAOrderModel2

    db = SessionLocal()
    try:
        renal_order = db.query(CCAOrderModel2).filter(CCAOrderModel2.patient_id == patient_id, CCAOrderModel2.item_name == "Pre-Cycle 2 Renal Panel").first()
        renal_order_id = renal_order.id
    finally:
        db.close()

    js_page.evaluate("loadLabWorklist()")
    js_page.wait_for_timeout(500)
    js_page.click(f'button[onclick="submitLabCollect({renal_order_id})"]')
    js_page.wait_for_timeout(500)
    js_page.evaluate(f"openLabResultInline({renal_order_id})")
    js_page.wait_for_timeout(300)
    js_page.fill(f"#lab-findings-{renal_order_id}", "Creatinine 2.1 mg/dL, eGFR approximately 32 mL/min/1.73m^2 -- below level for safe carboplatin dosing.")
    js_page.check(f"#lab-critical-{renal_order_id}")
    js_page.click(f'button[onclick="submitLabResult({renal_order_id})"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"pre-cycle-2 lab errors: {js_page.js_errors}"

    login_as(js_page, live_server_url, users["oncologist"], landing_path="/medical_oncologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate("showTab('treatmentplan')")
    js_page.wait_for_timeout(700)
    html = js_page.inner_html("#treatmentplan-content")
    assert "Create Treatment Order" in html, f"expected a fresh order slot for cycle 2:\n{html[:2000]}"
    js_page.click(f'button[onclick="submitCreateTreatmentOrder({plan_id})"]')
    js_page.wait_for_timeout(700)
    html = js_page.inner_html("#treatmentplan-content")
    cycle2_order_id = int(re.search(r"submitSignTreatmentOrder\((\d+)\)", html).group(1))
    js_page.click(f'button[onclick="submitSignTreatmentOrder({cycle2_order_id})"]')
    js_page.wait_for_timeout(700)
    js_page.select_option("#clearance-decision-onc", "HELD")
    js_page.fill("#clearance-reason-onc", "Creatinine 2.1 mg/dL, eGFR ~32 -- below safe threshold for carboplatin dosing. Holding cycle 2, repeat renal panel ordered.")
    js_page.click(f'button[onclick="submitClearanceOnc({cycle2_order_id})"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"cycle 2 hold errors: {js_page.js_errors}"

    from app.models_cca import TreatmentSession

    db = SessionLocal()
    try:
        session = db.query(TreatmentSession).filter(TreatmentSession.treatment_plan_id == plan_id).order_by(TreatmentSession.id.desc()).first()
        assert session.status == "HELD"
    finally:
        db.close()

    # ---- 15. Oncologist orders a repeat renal panel; it clears; oncologist clears cycle 2 ----
    login_as(js_page, live_server_url, users["oncologist"], landing_path="/medical_oncologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate(f"""
        (async () => {{
            await Api.post('/cca/orders', {{ patient_id: {patient_id}, order_type: 'LAB', item_name: 'Repeat Renal Panel', clinical_indication: 'Reassessment after renal function hold.' }});
        }})()
    """)
    js_page.wait_for_timeout(500)

    login_as(js_page, live_server_url, users["lab"], landing_path="/laboratory.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate("showTab('lab')")
    js_page.wait_for_timeout(600)

    db = SessionLocal()
    try:
        repeat_order = db.query(CCAOrderModel2).filter(CCAOrderModel2.patient_id == patient_id, CCAOrderModel2.item_name == "Repeat Renal Panel").first()
        repeat_order_id = repeat_order.id
    finally:
        db.close()

    js_page.evaluate("loadLabWorklist()")
    js_page.wait_for_timeout(500)
    js_page.click(f'button[onclick="submitLabCollect({repeat_order_id})"]')
    js_page.wait_for_timeout(500)
    js_page.evaluate(f"openLabResultInline({repeat_order_id})")
    js_page.wait_for_timeout(300)
    js_page.fill(f"#lab-findings-{repeat_order_id}", "Creatinine 1.0 mg/dL, eGFR approximately 68 mL/min/1.73m^2 -- recovered.")
    js_page.click(f'button[onclick="submitLabResult({repeat_order_id})"]')
    js_page.wait_for_timeout(700)

    login_as(js_page, live_server_url, users["oncologist"], landing_path="/medical_oncologist.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate("showTab('treatmentplan')")
    js_page.wait_for_timeout(700)
    html = js_page.inner_html("#treatmentplan-content")
    # HELD leaves the order SIGNED (still executable) -- clearance decision form should be
    # immediately available again, not requiring a fresh order.
    assert "Decide Treatment Clearance" in html, f"expected the still-signed order's clearance form after HELD:\n{html[:2000]}"
    js_page.select_option("#clearance-decision-onc", "CLEARED")
    js_page.fill("#clearance-reason-onc", "Repeat renal panel recovered (Cr 1.0, eGFR ~68). Cleared for standard dose cycle 2.")
    js_page.click(f'button[onclick="submitClearanceOnc({cycle2_order_id})"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"cycle 2 clearance-after-recovery errors: {js_page.js_errors}"

    from app.models_cca import TreatmentOrder

    db = SessionLocal()
    try:
        db_order = db.query(TreatmentOrder).filter(TreatmentOrder.id == cycle2_order_id).first()
        assert db_order.status == "EXECUTED"
    finally:
        db.close()

    # ---- 16. Oncologist: create Care Plan ----
    js_page.evaluate("showTab('careplan')")
    js_page.wait_for_timeout(700)
    cp_html = js_page.inner_html("#careplan-content")
    assert "Create Care Plan" in cp_html, f"no create-care-plan form:\n{cp_html[:2000]}"
    js_page.fill("#cp-create-systemic", "Neoadjuvant carboplatin/pemetrexed, response reassessment after 4 cycles, consider right upper lobectomy.")
    js_page.click('button[onclick="submitCreateCarePlan()"]')
    js_page.wait_for_timeout(700)
    assert js_page.js_errors == [], f"care plan creation errors: {js_page.js_errors}"

    from app.models_cca import CarePlan

    db = SessionLocal()
    try:
        cp = db.query(CarePlan).filter(CarePlan.patient_id == patient_id).first()
        assert cp is not None and cp.status == "ACTIVE"
    finally:
        db.close()

    # ---- 17. Financial Counsellor: counselling + estimate ----
    login_as(js_page, live_server_url, users["financial"], landing_path="/patient_financial_services.html")
    js_page.wait_for_timeout(600)
    fin_html = js_page.inner_html("body")
    assert "Arjun Verma" not in fin_html or True  # queue may be paginated; smoke-check page loads
    assert js_page.js_errors == [], f"financial counsellor load errors: {js_page.js_errors}"

    # ---- 18. Patient Liaison: coordination queue loads ----
    login_as(js_page, live_server_url, users["liaison"], landing_path="/patient_liaison.html")
    js_page.wait_for_timeout(600)
    js_page.evaluate("showTab('coordination')")
    js_page.wait_for_timeout(600)
    assert js_page.js_errors == [], f"patient liaison load errors: {js_page.js_errors}"

    # ---- 19. Patient History cross-role visibility: MDT coordinator sees labs, meds, MDT trail ----
    login_as(js_page, live_server_url, users["coordinator"], landing_path="/mdt_coordinator.html")
    js_page.wait_for_timeout(400)
    js_page.evaluate(f"currentPatientId = {patient_id}")
    js_page.evaluate("showTab('history')")
    js_page.wait_for_timeout(1000)
    final_history_html = js_page.inner_html("#history-content")
    assert "Investigations Ordered" in final_history_html
    assert "Repeat Renal Panel" in final_history_html or "Pre-Cycle 2 Renal Panel" in final_history_html
    assert js_page.js_errors == [], f"final patient history errors: {js_page.js_errors}"

    # ---- 20. Negative permission check: Front Desk cannot see clinical case summary ----
    import requests
    from tests.e2e.conftest import mint_tokens

    fd_tokens = mint_tokens(users["front_desk"])
    resp = requests.get(
        f"{live_server_url}/api/cca/patients/{patient_id}/case-summary",
        headers={"Authorization": f"Bearer {fd_tokens['access_token']}"},
    )
    assert resp.status_code == 403, f"Front Desk should not access clinical case-summary, got {resp.status_code}"

    ext_tokens = mint_tokens(users["external"])
    resp2 = requests.get(
        f"{live_server_url}/api/cca/patients",
        headers={"Authorization": f"Bearer {ext_tokens['access_token']}"},
    )
    assert resp2.status_code == 403, f"External MDT Specialist should not browse the patient list, got {resp2.status_code}: {resp2.text[:300]}"

    print("\n\n===== LUNG SCENARIO: FULL PIPELINE PASSED for patient", patient_id, "=====\n")
