"""
Medication Administration Record (MAR) -- Nursing Workflows. Closes the gap the current-state
audit found: medication tasks auto-generated by tasks_engine.py were completable via a generic
Task status change (a timestamp and free-text notes), but there was no dedicated per-dose
administration record with a real status (Given/Missed/Refused/Held) or an explicit route.

Deliberately a thin, separate model/router rather than adding these fields onto Task itself:
Task is the general nurse to-do list (labs, observations, medications, anything else a
consultation or a HeadNurse assigns); MAR is specifically the clinical-audit record of what
medication was actually given, when, by whom, and in what state -- a different lifecycle and a
different audience (a pharmacist/auditor reviewing MAR history shouldn't have to filter it out
of a general task list). task_id is optional: recording a PRN (as-needed) dose given on nursing
judgment, with no corresponding auto-generated Task, is a legitimate real-world case.
"""
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from ..auth import get_current_user, is_head_nurse, is_nurse, log_audit
from ..database import get_db
from ..models import MedicationAdministration, NurseAssignment, Patient, Task

router = APIRouter(tags=["mar"])


def _require_nursing_access(user: dict) -> None:
    if not (is_nurse(user) or is_head_nurse(user)):
        raise HTTPException(403, "Only nurses and head nurses can record medication administration")


def _get_assigned_patient(db: Session, patient_id: int, current_user: dict) -> Patient:
    patient = db.query(Patient).filter(
        Patient.id == patient_id, Patient.organization_id == current_user.get("organization_id")
    ).first()
    if not patient:
        raise HTTPException(404, "Patient not found")
    if is_nurse(current_user):
        assignment = db.query(NurseAssignment).filter(
            NurseAssignment.patient_id == patient_id, NurseAssignment.nurse_id == current_user["id"],
            NurseAssignment.status == "Active",
        ).first()
        if not assignment:
            raise HTTPException(403, "Not assigned to this patient")
    return patient


def _mar_out(m: MedicationAdministration) -> dict:
    return {
        "id": m.id, "patient_id": m.patient_id, "task_id": m.task_id, "drug_name": m.drug_name,
        "dose": m.dose, "route": m.route, "status": m.status, "notes": m.notes,
        "administered_by": m.administered_by, "administered_at": m.administered_at.isoformat(),
    }


class MARCreate(BaseModel):
    patient_id: int
    task_id: Optional[int] = None
    drug_name: str = Field(min_length=1, max_length=200)
    dose: Optional[str] = Field(default=None, max_length=100)
    route: Optional[str] = Field(default=None, max_length=100)
    status: str = Field(default="Given", pattern="^(Given|Missed|Refused|Held)$")
    notes: Optional[str] = None


@router.post("/api/ipd/medication-administrations", status_code=201)
def record_medication_administration(payload: MARCreate, current_user: dict = Depends(get_current_user), db: Session = Depends(get_db)):
    _require_nursing_access(current_user)
    _get_assigned_patient(db, payload.patient_id, current_user)
    org_id = current_user.get("organization_id")

    if payload.task_id is not None:
        task = db.query(Task).filter(Task.id == payload.task_id, Task.patient_id == payload.patient_id).first()
        if not task:
            raise HTTPException(404, "Task not found for this patient")

    record = MedicationAdministration(
        organization_id=org_id, patient_id=payload.patient_id, task_id=payload.task_id,
        drug_name=payload.drug_name, dose=payload.dose, route=payload.route, status=payload.status,
        notes=payload.notes, administered_by=current_user["id"],
    )
    db.add(record)
    db.commit()
    db.refresh(record)
    log_audit(db, current_user["id"], current_user["email"], org_id, "record_medication_administration",
              f"medication_administrations/{record.id}", "Success", f"drug={payload.drug_name} status={payload.status}")
    return _mar_out(record)


@router.get("/api/ipd/medication-administrations")
def list_medication_administrations(
    patient_id: int, current_user: dict = Depends(get_current_user), db: Session = Depends(get_db),
):
    _require_nursing_access(current_user)
    _get_assigned_patient(db, patient_id, current_user)
    records = db.query(MedicationAdministration).filter(
        MedicationAdministration.patient_id == patient_id
    ).order_by(MedicationAdministration.administered_at.desc()).all()
    return [_mar_out(r) for r in records]
