'use client'

import * as React from 'react'
import { ArrowRight, CheckCircle2, Settings, UserRound, Users } from 'lucide-react'
import { useRouter } from 'next/navigation'

import { demoPatient, useDemoAccess } from '@/components/demo-access-provider'
import { PageContainer, PageHeader } from '@/components/shell/page-container'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { demoRoles, roleConfig } from '@/lib/demo-access'

const selectClassName='h-10 w-full min-w-0 rounded-xl border border-input bg-input-background px-3 text-sm text-supporting shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring'
const labelClassName='text-xs font-medium text-metadata'

const metrics=[['Patients in OPD today','148','+12 vs 7-day average'],['Patients waiting','23','Average wait 18 minutes'],['Awaiting nurse intake','9','Oldest waiting 31 minutes'],['Diagnostics pending','31','7 delayed investigations'],['MDT cases pending','7','3 awaiting scheduling'],['Day-care chair utilization','22 / 28','79% utilization'],['No-shows','5','3 require follow-up'],['Pending financial clearance','15','4 overdue actions'],['Workflow completion','82%','Across today’s active episodes'],['Overdue tasks','18','6 escalated']]

export function AdminOperationsDashboard(){return <PageContainer><PageHeader title="Operations Dashboard" description="Operational workload, delays, capacity, and service performance"/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{metrics.map(([label,value,hint])=><Card key={label}><CardContent className="p-5"><p className="text-sm text-metadata">{label}</p><p className="mt-2 font-display text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-metadata">{hint}</p></CardContent></Card>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-2"><Card><CardHeader className="border-b border-divider"><CardTitle>Department workload</CardTitle></CardHeader><CardContent className="space-y-3 pt-6">{[['Medical Oncology','34 active','High'],['Nurse Intake','9 waiting','Warning'],['Radiology','12 pending','High'],['Pathology / Molecular','8 pending','Routine'],['Day Care','22 chairs occupied','High'],['Financial Counselling','15 pending','Warning']].map(([area,count,state])=><div key={area} className="flex items-center justify-between gap-3 rounded-lg border border-divider p-3"><div><p className="text-sm font-semibold text-supporting">{area}</p><p className="text-xs text-metadata">{count}</p></div><Badge variant={state==='Warning'?'warning':state==='High'?'information':'neutral'}>{state}</Badge></div>)}</CardContent></Card><Card><CardHeader className="border-b border-divider"><CardTitle>Critical operational alerts</CardTitle></CardHeader><CardContent className="space-y-3 pt-6">{[['Imaging report turnaround exceeded','Radiology · 4 cases','Escalated'],['Nurse intake backlog','Front Office · 9 waiting','Open'],['Treatment chair capacity above 75%','Day Care · 22/28','In progress'],['Financial clearance overdue','Patient Financial Services · 4 cases','Open']].map(([item,detail,status])=><div key={item} className="rounded-lg border border-warning/25 bg-warning-subtle p-4"><div className="flex justify-between gap-3"><p className="text-sm font-semibold text-warning-strong">{item}</p><Badge variant="warning">{status}</Badge></div><p className="mt-1 text-xs text-warning-strong">{detail}</p></div>)}</CardContent></Card></div></PageContainer>}

export function AdminPatientsQueue(){const router=useRouter();const {selectPatient,workflow}=useDemoAccess();const [query,setQuery]=React.useState('');const matches=`${demoPatient.name} ${demoPatient.mrn}`.toLowerCase().includes(query.trim().toLowerCase());return <PageContainer><PageHeader title="Patients" description="Operational patient and queue visibility"/><Card className="mb-6"><CardContent className="p-5"><label className={labelClassName}>Search patient<Input className="mt-1" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search by name or MRN"/></label></CardContent></Card><Card><CardHeader className="border-b border-divider"><CardTitle>Operational patient queue</CardTitle></CardHeader><CardContent className="pt-6">{matches?<article className="rounded-xl border border-white/75 bg-surface-elevated/75 p-5"><div className="grid gap-5 lg:grid-cols-3"><div><div className="flex gap-3"><span className="flex size-10 items-center justify-center rounded-full bg-brand-soft"><UserRound className="size-5"/></span><div><p className="font-display text-lg font-semibold">{demoPatient.name}</p><p className="text-xs text-metadata">MRN {demoPatient.mrn} · {demoPatient.age} years · {demoPatient.sex}</p></div></div><p className="mt-4 text-sm font-semibold text-supporting">Current department: Medical Oncology</p></div><div><p className={labelClassName}>Workflow / queue</p><p className="mt-1 text-sm font-semibold text-supporting">{workflow.phase} · Medical Oncology review queue</p><p className="mt-1 text-xs text-metadata">Assigned team: Medical Oncology · Next appointment 30 Aug 2026, 10:30</p></div><div><p className={labelClassName}>Operational blocker</p><p className="mt-1 text-sm font-semibold text-warning-strong">Diagnostics review delayed · overdue</p><p className="mt-1 text-xs text-metadata">Next action: escalate pending review to operational owner</p></div></div><div className="mt-5 flex justify-end border-t border-divider pt-5"><Button size="sm" onClick={()=>{selectPatient(demoPatient);router.push('/workflow-operations')}}>Open Operational View<ArrowRight/></Button></div></article>:<p className="py-16 text-center text-sm text-metadata">No matching operational patient.</p>}<p className="mt-4 rounded-lg border border-information/25 bg-information-subtle p-3 text-xs text-information-strong">Operational visibility only. Clinical diagnoses, staging, interpretations, notes, and treatment decisions are not editable.</p></CardContent></Card></PageContainer>}

const queues=[['Front Desk / Registration',12,4,38,2,1,'12 min'],['Nurse Intake',9,5,31,3,2,'18 min'],['Medical Oncology',14,8,27,4,2,'26 min'],['Surgical Oncology',4,3,12,1,0,'1.2 days'],['Radiation Oncology',6,4,9,2,1,'1.8 days'],['Radiology',12,7,24,5,2,'6.4 hours'],['Pathology / Molecular',8,6,18,4,1,'2.6 days'],['Lab / Phlebotomy',19,11,42,3,1,'78 min'],['Day-Care / Infusion',6,22,18,2,1,'34 min'],['MDT',7,3,8,3,1,'3.1 days'],['Financial Counselling',15,6,21,4,2,'1.4 days'],['Follow-up / Care Coordination',11,8,33,5,2,'2.2 days']] as const
const bottlenecks=[['Nurse Intake','9','31 minutes','High','Nurse Operations','Open'],['Radiology','5','9 hours','High','Imaging Operations','Escalated'],['Pathology / Molecular','4','3.8 days','High','Pathology Operations','In progress'],['Day Care','2','2 hours','Medium','Infusion Operations','Open'],['Financial Counselling','4','2.1 days','Medium','Financial Services','Open'],['Follow-up','5','4.2 days','High','Care Coordination','Escalated']]

export function WorkflowOperationsWorkspace(){const [statuses,setStatuses]=React.useState<Record<string,string>>({});const [notice,setNotice]=React.useState('');return <PageContainer><PageHeader title="Workflow Operations" description="Cross-department queues, turnaround times, and operational delays"/><Card className="mb-6"><CardHeader className="border-b border-divider"><CardTitle>Department queues</CardTitle></CardHeader><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-divider bg-surface-elevated/70 text-xs text-metadata"><tr>{['Area','Waiting','In progress','Completed','Delayed','Escalated','Avg TAT','Action'].map((h)=><th key={h} className="px-4 py-3 font-semibold">{h}</th>)}</tr></thead><tbody>{queues.map(([area,waiting,progress,completed,delayed,escalated,tat])=><tr key={area} className="border-b border-divider"><td className="px-4 py-3 font-semibold text-supporting">{area}</td>{[waiting,progress,completed,delayed,escalated,tat].map((value,index)=><td key={index} className="px-4 py-3 text-supporting">{value}</td>)}<td className="px-4 py-3"><Button size="sm" variant="ghost" onClick={()=>setNotice(`Opened ${area} queue detail`)}>View queue</Button></td></tr>)}</tbody></table></CardContent></Card><Card><CardHeader className="border-b border-divider"><CardTitle>Operational bottlenecks</CardTitle></CardHeader><CardContent className="grid gap-3 pt-6 sm:grid-cols-2 lg:grid-cols-3">{bottlenecks.map(([area,count,oldest,severity,owner,status])=><div key={area} className="rounded-lg border border-divider p-4"><div className="flex justify-between gap-3"><p className="font-semibold text-supporting">{area}</p><Badge variant={severity==='High'?'warning':'neutral'}>{severity}</Badge></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><p><span className="text-metadata">Count</span><br/><strong>{count}</strong></p><p><span className="text-metadata">Oldest</span><br/><strong>{oldest}</strong></p><p><span className="text-metadata">Owner</span><br/><strong>{owner}</strong></p><p><span className="text-metadata">Status</span><br/><strong>{statuses[area]??status}</strong></p></div><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>setNotice(`${area} reassignment recorded`)}>Reassign owner</Button><Button size="sm" variant="outline" onClick={()=>setStatuses((current)=>({...current,[area]:'Escalated'}))}>Escalate</Button><Button size="sm" variant="ghost" onClick={()=>setStatuses((current)=>({...current,[area]:'Resolved'}))}>Resolve</Button></div></div>)}</CardContent></Card>{notice?<p className="mt-4 text-sm font-semibold text-success-strong">{notice}</p>:null}<p className="mt-4 rounded-lg border border-warning/25 bg-warning-subtle p-3 text-xs text-warning-strong">Operational queue controls only; clinical decisions and clinician-owned content are unavailable.</p></PageContainer>}

export function UsersRolesWorkspace(){const [userStatus,setUserStatus]=React.useState('Active');const [assignedRole,setAssignedRole]=React.useState('Front Desk / Registration');const [notice,setNotice]=React.useState('');return <PageContainer><PageHeader title="Users & Roles" description="Safe demonstration access and role visibility" actions={<Button size="sm" onClick={()=>setNotice('Demo user draft created')}><Users/>Create User</Button>}/><Card className="mb-6"><CardHeader className="border-b border-divider"><CardTitle>Demo users</CardTitle></CardHeader><CardContent className="pt-6"><div className="grid gap-4 rounded-lg border border-divider p-4 sm:grid-cols-2 lg:grid-cols-6"><div><p className={labelClassName}>User</p><p className="mt-1 text-sm font-semibold">Demo Operations User</p></div><label className={labelClassName}>Role<select className={`${selectClassName} mt-1`} value={assignedRole} onChange={(event)=>setAssignedRole(event.target.value)}>{demoRoles.map((role)=><option key={role.id}>{role.label}</option>)}</select></label><label className={labelClassName}>Department<Input className="mt-1" defaultValue="Operations"/></label><label className={labelClassName}>Status<select className={`${selectClassName} mt-1`} value={userStatus} onChange={(event)=>setUserStatus(event.target.value)}><option>Active</option><option>Inactive</option><option>Suspended</option><option>Pending</option></select></label><div><p className={labelClassName}>Last login</p><p className="mt-2 text-sm font-semibold">24 Aug 2026 · 14:20</p></div><div className="flex flex-wrap items-end gap-2"><Button size="sm" variant="outline" onClick={()=>setUserStatus(userStatus==='Active'?'Inactive':'Active')}>{userStatus==='Active'?'Deactivate':'Reactivate'}</Button><Button size="sm" variant="ghost" onClick={()=>setNotice('Demo access reset')}>Reset access</Button></div></div>{notice?<p className="mt-3 text-sm font-semibold text-success-strong">{notice}</p>:null}</CardContent></Card><Card><CardHeader className="border-b border-divider"><CardTitle>Configured roles and access scope</CardTitle></CardHeader><CardContent className="grid gap-3 pt-6 sm:grid-cols-2 lg:grid-cols-3">{demoRoles.map((role)=>{const config=roleConfig[role.roleId];return <div key={role.id} className="rounded-lg border border-divider p-4"><div className="flex justify-between gap-2"><p className="text-sm font-semibold text-supporting">{role.label}</p><Badge variant="success">Active</Badge></div><p className="mt-2 text-xs text-metadata">{config.patientAccess} patient scope · {config.modules.length} modules · {config.actions.length} actions</p><Button className="mt-3" size="sm" variant="ghost">View permissions</Button></div>})}</CardContent></Card><p className="mt-4 text-xs text-metadata">No passwords, hashes, secrets, tokens, or enterprise identity infrastructure are exposed.</p></PageContainer>}

const auditExamples=[['Front Desk User','Front Desk / Registration','DEMO-ONC-02481','Registration','Patient registered','23 Aug 2026 · 10:30','Clinician-entered'],['Nurse Navigator','Nurse Navigator','DEMO-ONC-02481','Nurse Intake','Intake completed','23 Aug 2026 · 10:42','Clinician-entered'],['Medical Oncologist','Medical Oncologist','DEMO-ONC-02481','Doctor OPD','Consultation signed','23 Aug 2026 · 11:25','Signed / finalized'],['Pathologist','Pathologist / Molecular Diagnostics','MDT-DEMO-118','Pathology','Report finalized','24 Aug 2026 · 09:10','Signed / finalized'],['Radiologist','Radiologist','DEMO-ONC-02481','Radiology','Report finalized','24 Aug 2026 · 10:05','Signed / finalized'],['MDT Clinician','Medical Oncologist','MDT-DEMO-118','MDT','Decision signed','24 Aug 2026 · 12:40','Signed / finalized'],['Financial Counsellor','Patient Financial Services','DEMO-ONC-02481','Finance','Financial clearance updated','24 Aug 2026 · 14:05','User-entered'],['Admin User','Admin / Operations','System','Users & Roles','Role assignment changed','24 Aug 2026 · 14:20','Administrative']]

export function AuditActivityWorkspace(){const {events}=useDemoAccess();const [filter,setFilter]=React.useState('All modules');const rows=[...events.map((e)=>[e.actor,e.role,'DEMO-ONC-02481',e.source,e.action,e.timestamp,'Application event']),...auditExamples];return <PageContainer><PageHeader title="Audit & Activity" description="Application actions, actors, sources, and state changes"/><Card className="mb-6"><CardContent className="grid gap-3 p-5 sm:grid-cols-2 lg:grid-cols-6"><Input placeholder="User"/><Input placeholder="Role"/><Input placeholder="Patient / case"/><select className={selectClassName} value={filter} onChange={(event)=>setFilter(event.target.value)}><option>All modules</option><option>Registration</option><option>Nurse Intake</option><option>Doctor OPD</option><option>Pathology</option><option>Radiology</option><option>MDT</option><option>Finance</option></select><Input placeholder="Action type"/><Input type="date" aria-label="Audit date"/></CardContent></Card><Card><CardContent className="max-h-[520px] overflow-auto p-0"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="sticky top-0 border-b border-divider bg-surface-elevated text-xs text-metadata"><tr>{['User','Role','Patient / case','Module','Action','Timestamp','Source / review state'].map((h)=><th key={h} className="px-4 py-3 font-semibold">{h}</th>)}</tr></thead><tbody>{rows.filter((row)=>filter==='All modules'||row[3]===filter).map((row,index)=><tr key={`${row[4]}-${index}`} className="border-b border-divider">{row.map((value,i)=><td key={i} className="px-4 py-3 text-supporting">{value}</td>)}</tr>)}</tbody></table></CardContent></Card><p className="mt-4 text-xs text-metadata">Application audit events only. No hidden reasoning or chain-of-thought is exposed.</p></PageContainer>}

export function AdminSettingsWorkspace(){const [notice,setNotice]=React.useState('');return <PageContainer><PageHeader title="Settings" description="Operational and system configuration"/><div className="grid gap-6 xl:grid-cols-2">{[['Departments','Medical Oncology · Surgery · Radiation · Diagnostics'],['Locations','Main OPD · Day Care · Imaging · Laboratory'],['Working hours','Mon–Sat · 08:00–18:00'],['Appointment types','New consultation · Follow-up · Treatment'],['Queue rules','Priority and appointment-time ordering'],['Notification rules','Operational reminders and escalations'],['Role configuration','Existing demonstration role scopes'],['Demo configuration','Local browser workflow state'],['Service availability','Department operating status']].map(([title,value])=><Card key={title}><CardHeader className="border-b border-divider"><CardTitle className="text-base">{title}</CardTitle></CardHeader><CardContent className="pt-5"><Input defaultValue={value}/><Button className="mt-3" size="sm" variant="outline" onClick={()=>setNotice(`${title} configuration saved`)}><Settings/>Save</Button></CardContent></Card>)}</div>{notice?<p className="mt-4 flex items-center gap-2 text-sm font-semibold text-success-strong"><CheckCircle2 className="size-4"/>{notice}</p>:null}<p className="mt-4 rounded-lg border border-information/25 bg-information-subtle p-3 text-xs text-information-strong">Clinical reasoning, staging rules, guideline logic, and treatment algorithms are not configurable here.</p></PageContainer>}
