'use client'

import * as React from 'react'
import Link from 'next/link'
import { AlertTriangle, ArrowRight, CheckCircle2, FileText, Search, ShieldAlert, Sparkles, Stethoscope, UserRound } from 'lucide-react'
import { demoPatient, useDemoAccess } from '@/components/demo-access-provider'
import { Button, buttonVariants } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'

function SummaryItem({ label, value }: { label: string; value: React.ReactNode }) {
  return <div className="min-w-0"><dt className="text-[10px] font-semibold uppercase tracking-[0.12em] text-metadata">{label}</dt><dd className="mt-1 text-sm font-medium leading-5 text-supporting">{value}</dd></div>
}

export function DoctorPatientSearchAndSummary() {
  const { role, selectedPatient, selectPatient, workflow } = useDemoAccess()
  const [query, setQuery] = React.useState('')
  const [searched, setSearched] = React.useState(false)
  const [opened, setOpened] = React.useState(false)
  const matches = query.trim() && [demoPatient.name, demoPatient.mrn, demoPatient.mobile].some((value) => value.toLowerCase().includes(query.trim().toLowerCase()))

  return <div className="mb-6 space-y-5">
    <Card className="shadow-soft-sm"><CardContent className="p-5 sm:p-6">
      <div className="mb-4 flex items-start gap-3"><span className="aivana-gradient flex size-9 shrink-0 items-center justify-center rounded-md text-primary-foreground shadow-soft-sm"><Search className="size-4" /></span><div><h3 className="font-display text-base font-semibold">Find a patient</h3><p className="mt-0.5 text-xs text-metadata">Search by name, MRN or mobile number · fictional demo register</p></div></div>
      <div className="flex flex-col gap-3 sm:flex-row"><Input aria-label="Doctor patient search" placeholder="Name, MRN or mobile number" value={query} onChange={(event) => { setQuery(event.target.value); setSearched(false) }} onKeyDown={(event) => { if (event.key === 'Enter') setSearched(true) }} /><Button type="button" onClick={() => setSearched(true)}><Search />Search</Button></div>
      {searched ? <div className="mt-4">{matches ? <div className="flex flex-wrap items-center gap-4 rounded-md bg-success-subtle px-4 py-3"><span className="flex size-10 items-center justify-center rounded-full bg-surface"><UserRound className="size-5" /></span><div className="min-w-0 flex-1"><p className="font-semibold text-supporting">{demoPatient.name}</p><p className="mt-0.5 text-xs text-metadata">MRN {demoPatient.mrn} · {demoPatient.age} years · {demoPatient.sex}</p><p className="mt-1 text-xs text-supporting">{demoPatient.stage} breast cancer · {demoPatient.treatment} · {demoPatient.treatmentPoint}</p></div><Button type="button" onClick={() => { selectPatient(demoPatient); setOpened(true) }}>Open Patient<ArrowRight /></Button></div> : <div className="rounded-md bg-surface-app px-4 py-3"><p className="text-sm font-medium text-supporting">No matching fictional patient</p><p className="mt-1 text-xs text-metadata">Try Sunita Patil, DEMO-ONC-02481, or the demo mobile number.</p></div>}</div> : null}
      {opened ? <p role="status" className="mt-3 flex items-center gap-2 text-xs font-medium text-success-strong"><CheckCircle2 className="size-4" />Patient opened across connected demo modules.</p> : null}
    </CardContent></Card>

    <Card id="patient-summary" variant="elevated" className="aivana-accent-line overflow-hidden"><CardHeader className="border-b border-divider bg-surface pb-5 pl-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="flex min-w-0 items-center gap-3"><span className="aivana-gradient-soft flex size-11 shrink-0 items-center justify-center rounded-full text-supporting"><UserRound className="size-5" /></span><div className="min-w-0"><CardTitle className="text-lg">{selectedPatient.name}</CardTitle><CardDescription className="mt-1">MRN {selectedPatient.mrn} · {selectedPatient.age} years · {selectedPatient.sex}</CardDescription><p className="mt-1 text-sm font-medium text-supporting">{selectedPatient.diagnosis} · {selectedPatient.stage}</p></div></div><div className="flex flex-wrap gap-2"><Link href="#consultation-scribe" className={buttonVariants({ size: 'sm' })}><Stethoscope className="size-4" />Start Consultation</Link><a href="#doctor-full-record" className={buttonVariants({ variant: 'secondary', size: 'sm' })}>Continue Consultation</a><a href="#doctor-full-record" className={buttonVariants({ variant: 'ghost', size: 'sm' })}><FileText />View Full Record</a></div></div></CardHeader>
      <CardContent className="space-y-6 p-5 sm:p-6">
        <section aria-labelledby="oncology-snapshot-title"><h3 id="oncology-snapshot-title" className="text-xs font-semibold uppercase tracking-[0.14em] text-metadata">Oncology snapshot</h3><dl className="mt-3 grid gap-x-6 gap-y-4 sm:grid-cols-2 lg:grid-cols-3"><SummaryItem label="Diagnosis" value="Left breast invasive ductal carcinoma" /><SummaryItem label="Histology" value="Grade 2 invasive ductal carcinoma" /><SummaryItem label="Stage" value={selectedPatient.stage} /><SummaryItem label="Biomarkers" value={selectedPatient.biology} /><SummaryItem label="Surgery" value="Lumpectomy · June 2026" /><SummaryItem label="Current systemic therapy" value={`${selectedPatient.treatment} · ${selectedPatient.treatmentPoint}`} /></dl></section>
        {role.roleId === 'radiation-oncology' ? <section className="border-t border-divider pt-6" aria-labelledby="radiation-context-title"><h3 id="radiation-context-title" className="text-xs font-semibold uppercase tracking-[0.14em] text-metadata">Radiation context</h3><dl className="mt-3 grid gap-x-6 gap-y-4 sm:grid-cols-2 lg:grid-cols-3"><SummaryItem label="TNM / ECOG" value="pT2N0M0 · ECOG 1"/><SummaryItem label="Previous radiotherapy" value="None documented"/><SummaryItem label="Radiation indication" value="Adjuvant review after systemic therapy"/><SummaryItem label="Treatment site / intent" value="Left breast · clinician confirmation required"/><SummaryItem label="Workflow stage" value="Radiation consultation"/><SummaryItem label="Imaging / pathology" value="Reports available for clinician review"/></dl><div className="mt-4 rounded-lg border border-brand/25 bg-brand-soft p-4"><p className="text-xs font-medium text-metadata">Next radiation action</p><p className="mt-1 text-sm font-semibold text-supporting">Review imaging and finalize simulation / radiation planning</p></div></section> : null}
        <div className="grid gap-6 border-t border-divider pt-6 lg:grid-cols-2"><section aria-labelledby="today-context-title"><h3 id="today-context-title" className="text-xs font-semibold uppercase tracking-[0.14em] text-metadata">Today's clinical context</h3><dl className="mt-3 grid gap-4 sm:grid-cols-2"><SummaryItem label="Reason for visit" value="Cycle 2 toxicity and readiness review" /><SummaryItem label="Recent symptoms" value="Fatigue, mild nausea, reduced appetite" /><SummaryItem label="Nurse handoff" value="Completed · Routine clinician review" /><SummaryItem label="Relevant alert" value={<span className="flex items-start gap-1.5 text-critical-strong"><AlertTriangle className="mt-0.5 size-3.5 shrink-0" />Paclitaxel severe hypersensitivity ADR</span>} /></dl></section><section aria-labelledby="current-work-title"><h3 id="current-work-title" className="text-xs font-semibold uppercase tracking-[0.14em] text-metadata">Current work</h3><dl className="mt-3 grid gap-4 sm:grid-cols-2"><SummaryItem label="Medications" value="Antiemetic and post-treatment supportive regimen reconciled" /><SummaryItem label="Investigations" value={`Lab: ${workflow.lab} · Radiology: ${workflow.radiology}`} /><SummaryItem label="Current phase" value={workflow.phase} /><SummaryItem label="What happens next" value={workflow.nextLocation} /></dl></section></div>
        {role.roleId !== 'surgical-oncology' && role.roleId !== 'radiation-oncology' ? <div className="flex flex-col gap-4 rounded-lg bg-ai-panel p-4 sm:flex-row sm:items-center"><span className="flex size-9 shrink-0 items-center justify-center rounded-md bg-ai-highlight text-supporting"><Sparkles className="size-4" /></span><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-supporting">AI Scribe</p><p className="mt-0.5 text-xs text-metadata">Clinical note draft ready for clinician review · {workflow.scribeStatus}</p></div><Link href="#consultation-scribe" className={buttonVariants({ size: 'sm' })}>Open Scribe<ArrowRight /></Link></div> : null}
        <div className="flex items-start gap-2 border-t border-divider pt-4 text-xs text-metadata"><ShieldAlert className="mt-0.5 size-4 shrink-0" /><p>Fictional demo patient and browser-local workflow state. No MPI, EHR, HMIS, or external clinical system is connected.</p></div>
      </CardContent>
    </Card>
  </div>
}
