'use client'

import * as React from 'react'
import { ArrowRight, CheckCircle2, Clock3, ShieldAlert, UserRound } from 'lucide-react'
import { useDemoAccess } from '@/components/demo-access-provider'
import { PageContainer, PageHeader } from '@/components/shell/page-container'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { ActionId, roleConfig } from '@/lib/demo-access'

const actionMap: Partial<Record<string, Array<[ActionId,string,string]>>> = {
  registration: [['complete-registration','Registration completed','Registration'],['handoff-nurse','Handoff to Nurse','Registration']],
  nurse: [['complete-intake','Nurse Intake completed','Nurse Intake'],['handoff-doctor','Handoff to Medical Oncology','Nurse Intake']],
  doctor: [['complete-opd','OPD completed','Doctor OPD'],['send-mdt','Case sent to MDT','Doctor OPD'],['draft-care-plan','Care plan drafted','Doctor OPD']],
  'surgical-oncology': [['complete-opd','Surgical oncology review completed','Doctor OPD'],['send-mdt','Open MDT case','Doctor OPD']],
  'radiation-oncology': [['complete-opd','Radiation oncology review completed','Doctor OPD'],['send-mdt','Open MDT case','Doctor OPD']],
  lab: [['complete-lab','Result ready for clinician review','Lab']],
  radiology: [['complete-radiology','Report ready for clinician review','Radiology']],
  'mdt-coordinator': [['assemble-packet','MDT packet assembled','MDT / Tumour Board'],['schedule-board','MDT board scheduled','MDT / Tumour Board']],
  'mdt-clinician': [['comment-mdt','External MDT comment recorded','MDT / Tumour Board'],['approve-mdt','MDT recommendation approved','MDT / Tumour Board']],
  navigator: [['create-follow-up','Patient follow-up task created','NEXUS']],
  finance: [['update-finance','Financial workflow status updated','Conversion / Finance']],
}

export function RoleWorkspace() {
  const { role, events, tasks, workflow, performAction } = useDemoAccess()
  const config = roleConfig[role.roleId]
  const [notice,setNotice] = React.useState('')
  const actions = actionMap[role.roleId] ?? []
  const roleDestinations:Record<string,string[]>={registration:['Registration'],nurse:['Nurse Intake'],doctor:['Doctor OPD','Medical Oncology','Treatment Planning'],'surgical-oncology':['Doctor OPD','Treatment Planning'],'radiation-oncology':['Doctor OPD','Treatment Planning'],lab:['Lab / Radiology'],radiology:['Lab / Radiology'],'mdt-coordinator':['MDT / Tumour Board'],'mdt-clinician':['MDT / Tumour Board'],navigator:['NEXUS','Patient Journey'],finance:['Conversion / Finance'],admin:[]}
  const assignedTasks=tasks.filter((task)=>(roleDestinations[role.roleId]??[]).includes(task.destination)).slice(0,4)
  return <PageContainer>
    <PageHeader title={`${role.shortLabel} work queue`} description="Role-specific operational workspace connected to one fictional oncology patient journey." actions={<Badge variant="information">Demo role</Badge>} />
    <div className="mb-6 flex items-start gap-3 rounded-xl border border-information/25 bg-information-subtle/80 px-4 py-3 text-information-strong shadow-sm"><ShieldAlert className="mt-0.5 size-4 shrink-0" /><div><p className="text-sm font-semibold">Demonstration identity and permissions</p><p className="mt-0.5 text-xs leading-relaxed">These roles and permissions are product assumptions, not documented CCA IAM policy. Actions are local workflow demonstrations only.</p></div></div>
    <Card variant="gradient" className="aivana-accent-line mb-6 overflow-hidden"><CardContent className="grid gap-5 p-5 md:grid-cols-4"><div className="flex items-center gap-3 md:col-span-2"><span className="flex size-11 items-center justify-center rounded-xl bg-white/80 text-brand-deep shadow-sm"><UserRound className="size-5" /></span><div><p className="font-display font-semibold">Sunita Patil <span className="text-xs font-normal text-metadata">(Fictional)</span></p><p className="mt-0.5 text-xs text-metadata">MRN DEMO-ONC-02481 · Breast Cancer · Stage IIA</p></div></div><div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-metadata">Current treatment</p><p className="mt-1 text-sm font-semibold">AC chemotherapy · C2D8</p></div><div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-metadata">Viewing as</p><p className="mt-1 text-sm font-semibold">{role.label}</p></div></CardContent></Card>
    <Card className="mb-6"><CardHeader className="border-b border-divider"><div className="flex items-start justify-between gap-3"><div><CardTitle>Assigned workflow tasks</CardTitle><CardDescription className="mt-1">Role-owned actions for the current fictional patient</CardDescription></div><Badge variant="information">Demo state · {workflow.phase}</Badge></div></CardHeader><CardContent className="grid gap-3 pt-6 lg:grid-cols-2">{assignedTasks.length?assignedTasks.map((task)=><div key={task.id} className="rounded-md border border-border p-4"><p className="text-sm font-semibold text-supporting">{task.task}</p><div className="mt-3 grid grid-cols-2 gap-3 text-xs"><p><span className="text-metadata">Owner</span><br/><strong>{task.owner??task.destination}</strong></p><p><span className="text-metadata">Status</span><br/><strong>{task.status}</strong></p><p><span className="text-metadata">Priority</span><br/><strong>{task.priority??'Routine'}</strong></p><p><span className="text-metadata">Next action</span><br/><strong>{task.nextAction??`Open ${task.destination}`}</strong></p></div></div>):<p className="text-sm text-metadata">No active role-owned task. Next destination: {workflow.nextLocation}.</p>}</CardContent></Card>
    <div className="grid gap-6 xl:grid-cols-3"><Card className="xl:col-span-2"><CardHeader className="border-b border-divider"><CardTitle>{role.shortLabel} queue</CardTitle><CardDescription>Fictional items assigned to this stakeholder workspace</CardDescription></CardHeader><CardContent className="grid gap-4 pt-6 sm:grid-cols-2">{config.queue.map((item,index)=><div key={item} className="flex items-start gap-3 rounded-lg border border-border p-4"><span className="flex size-8 shrink-0 items-center justify-center rounded-md bg-surface-elevated text-sm font-semibold">{index+1}</span><div><p className="text-sm font-semibold text-supporting">{item}</p><p className="mt-1 text-xs text-metadata">{index % 2 === 0 ? 'Awaiting review' : 'Open'} · Fictional demo queue</p><Badge className="mt-3" variant={index === 0 ? 'warning' : 'neutral'}>{index === 0 ? 'Priority' : 'Routine'}</Badge></div></div>)}</CardContent></Card><Card variant="elevated"><CardHeader className="border-b border-divider"><CardTitle>Permitted actions</CardTitle><CardDescription>Checked centrally before execution</CardDescription></CardHeader><CardContent className="space-y-3 pt-6">{actions.length ? actions.map(([id,label,source])=><Button key={id} type="button" variant="outline" className="w-full justify-between" onClick={()=>setNotice(performAction(id,label,source) ? `${label} recorded` : 'Action blocked by role permission')}>{label}<ArrowRight /></Button>) : <p className="text-sm text-metadata">This role has visibility-only access in the current demonstration.</p>}{notice ? <div className="flex gap-2 rounded-md border border-success/30 bg-success-subtle p-3 text-xs text-success-strong"><CheckCircle2 className="size-4 shrink-0" />{notice}</div> : null}{role.roleId === 'mdt-clinician' ? <p className="rounded-md border border-warning/30 bg-warning-subtle p-3 text-xs text-warning-strong">Assigned-case view only. Anonymous presentation is enabled; finance, administration, unrelated patients, and unnecessary identifiers are excluded.</p> : null}</CardContent></Card></div>
    <Card className="mt-6"><CardHeader className="border-b border-divider"><CardTitle>Connected journey and audit trail</CardTitle><CardDescription>Visible product-demonstration provenance for meaningful actions</CardDescription></CardHeader><CardContent className="divide-y divide-divider p-0">{events.slice(0,8).map((event)=><div key={event.id} className="flex gap-3 px-6 py-4"><Clock3 className="mt-0.5 size-4 shrink-0 text-metadata"/><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-supporting">{event.action}</p><p className="mt-1 text-xs text-metadata">{event.actor} · {event.role}</p><p className="mt-1 text-xs text-metadata">{event.timestamp} · Source: {event.source}</p></div></div>)}</CardContent></Card>
  </PageContainer>
}
