'use client'

import * as React from 'react'
import { AlertTriangle, ChevronRight, FileCheck2, FileClock, FileQuestion, FileText, FolderOpen, ShieldAlert, UserRound } from 'lucide-react'
import { PageContainer, PageHeader } from '@/components/shell/page-container'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { cn } from '@/lib/utils'
import { StakeholderWorkflowPanel } from '@/components/stakeholder-workflow-panel'

type Status = 'Available' | 'Under review' | 'Missing' | 'Pending upload'
type Document = { id: string; name: string; type: string; category: string; date: string; owner: string; status: Status; review: string; summary: string; team: string; next: string }
const documents: Document[] = [
  { id: 'referral', name: 'Oncology referral and registration summary', type: 'Referral packet', category: 'Referral / Registration', date: '18 Jun 2026', owner: 'Patient Access', status: 'Available', review: 'Verified', summary: 'Fictional referral indication, patient identity, contact information, and registration context.', team: 'Patient Access', next: 'No immediate workflow action.' },
  { id: 'opd-note', name: 'Medical Oncology OPD consultation', type: 'Clinical note', category: 'Clinical Notes', date: '23 Aug 2026', owner: 'Medical Oncologist', status: 'Available', review: 'Clinician approved', summary: 'Fictional assessment of treatment-related fatigue and nausea with diagnosis, plan, safety-net advice, and follow-up.', team: 'Medical Oncology', next: 'Use clinician-approved note in the next care review.' },
  { id: 'cbc', name: 'CBC and chemistry result set', type: 'Laboratory result', category: 'Laboratory', date: '23 Aug 2026', owner: 'Laboratory Demo', status: 'Under review', review: 'Clinician review required', summary: 'Fictional CBC includes haemoglobin 9.4 g/dL and ANC 0.7 ×10⁹/L with chemotherapy-relevant chemistry markers.', team: 'Medical Oncology', next: 'Review flagged values and document clinical interpretation.' },
  { id: 'ct-report', name: 'CT chest, abdomen and pelvis report', type: 'Radiology report', category: 'Radiology', date: '22 Aug 2026', owner: 'Radiologist', status: 'Available', review: 'Awaiting clinician acknowledgement', summary: 'Fictional staging CT report describing post-operative change without reported distant metastatic disease.', team: 'Medical Oncology / Radiology', next: 'Correlate report with pathology and clinical context.' },
  { id: 'pathology', name: 'Definitive surgical pathology report', type: 'Pathology report', category: 'Pathology', date: 'Expected 24 Aug 2026', owner: 'Pathology Coordinator', status: 'Missing', review: 'Not available', summary: 'Definitive formatted report is not represented in this prototype. Structured fictional pathology context exists in the MDT case summary only.', team: 'Pathology', next: 'Obtain and verify the responsible-clinician source document.' },
  { id: 'treatment', name: 'Adjuvant systemic treatment plan', type: 'Treatment document', category: 'Treatment', date: '20 Aug 2026', owner: 'Medical Oncology', status: 'Available', review: 'Current plan', summary: 'Fictional AC chemotherapy pathway, supportive-care context, and planned readiness checks.', team: 'Medical Oncology / Day Care', next: 'Confirm cycle readiness through clinician-led review.' },
  { id: 'mdt', name: 'MDT case summary and outcome', type: 'Tumour Board summary', category: 'MDT / Tumour Board', date: '29 Aug 2026', owner: 'Tumour Board Coordinator', status: 'Pending upload', review: 'MDT scheduled', summary: 'Prepared fictional case context; final multidisciplinary discussion and outcome have not occurred.', team: 'MDT Coordination', next: 'Complete clinician-led MDT and record the approved outcome.' },
  { id: 'consent', name: 'Registration and privacy consent summary', type: 'Consent placeholder', category: 'Consent', date: '23 Aug 2026', owner: 'Front Office', status: 'Available', review: 'Demo completion recorded', summary: 'Fictional workflow confirmation only; this is not a legally binding electronic consent document.', team: 'Patient Access', next: 'Treating team confirms consent requirements for each clinical procedure.' },
  { id: 'estimate', name: 'Treatment financial estimate', type: 'Financial workflow document', category: 'Financial', date: '23 Aug 2026', owner: 'Conversion / Finance', status: 'Under review', review: 'Counselling pending', summary: 'Fictional drug and service estimate derived from the demonstration treatment plan.', team: 'Conversion / Finance', next: 'Complete financial counselling and record funding status.' },
]
const categories = ['Referral / Registration','Clinical Notes','Laboratory','Radiology','Pathology','Treatment','MDT / Tumour Board','Consent','Financial']
const statusVariant = { Available: 'success', 'Under review': 'warning', Missing: 'critical', 'Pending upload': 'neutral' } as const

export default function DocumentsPage() {
  const [selectedId, setSelectedId] = React.useState('pathology')
  const [category, setCategory] = React.useState('All documents')
  const selected = documents.find((document) => document.id === selectedId) ?? documents[0]
  const visible = category === 'All documents' ? documents : documents.filter((document) => document.category === category)
  return <PageContainer>
    <PageHeader title="Documents" description="Centralize the clinical documents needed across the oncology pathway." actions={<Badge variant="information">Fictional demo data</Badge>} />
    <StakeholderWorkflowPanel module="documents" />
    <div className="mb-6 flex items-start gap-3 rounded-lg border border-information/30 bg-information-subtle px-4 py-3 text-information-strong"><ShieldAlert className="mt-0.5 size-4 shrink-0" /><div><p className="text-sm font-medium">Workflow/document visibility demonstration only</p><p className="mt-0.5 text-xs">All data is fictional. Nothing is stored, retrieved, uploaded, persisted, or transmitted, and no EHR, HIS, PACS, or document-management integration exists.</p></div></div>
    <Card className="mb-6 bg-surface-clinical"><CardContent className="grid gap-5 p-5 sm:grid-cols-2 xl:grid-cols-5"><div className="flex items-center gap-3 sm:col-span-2"><span className="flex size-10 items-center justify-center rounded-full bg-surface"><UserRound className="size-5" /></span><div><p className="font-display font-semibold">Sunita Patil <span className="text-xs font-normal text-metadata">(Fictional)</span></p><p className="text-xs text-metadata">MRN DEMO-ONC-02481 · 39 years · Female</p></div></div><div><p className="text-xs uppercase tracking-wider text-metadata">Diagnosis / stage</p><p className="mt-1 text-sm font-medium text-supporting">Breast cancer · Stage IIA</p></div><div><p className="text-xs uppercase tracking-wider text-metadata">Treatment</p><p className="mt-1 text-sm font-medium text-supporting">AC chemotherapy · C2D8</p></div><div><p className="text-xs uppercase tracking-wider text-metadata">Document set</p><p className="mt-1 text-sm font-medium text-supporting">7 fictional records</p></div></CardContent></Card>

    <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
      ['Missing pathology report','Responsible source document unavailable','critical',FileQuestion],['Laboratory results awaiting review','Flagged fictional CBC requires clinician review','warning',FileClock],
      ['Staging imaging report available','CT report ready for clinical correlation','success',FileCheck2],['MDT summary pending','Discussion scheduled for 29 Aug','information',FileText],
    ].map(([title,detail,variant,Icon]) => <Card key={title as string}><CardContent className="flex gap-3 p-5"><span className={cn('flex size-9 shrink-0 items-center justify-center rounded-md', variant === 'critical' ? 'bg-critical-subtle text-critical-strong' : variant === 'warning' ? 'bg-warning-subtle text-warning-strong' : variant === 'success' ? 'bg-success-subtle text-success-strong' : 'bg-information-subtle text-information-strong')}><Icon className="size-4" /></span><div><p className="text-sm font-semibold text-supporting">{title as string}</p><p className="mt-1 text-xs text-metadata">{detail as string}</p></div></CardContent></Card>)}
    </div>

    <div className="grid gap-6 xl:grid-cols-3">
      <div className="space-y-6 xl:col-span-2">
        <Card><CardHeader className="border-b border-divider"><CardTitle>Document categories</CardTitle><CardDescription>Filter the fictional pathway record by workflow</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-2 pt-6"><Button type="button" size="sm" variant={category === 'All documents' ? 'primary' : 'outline'} onClick={() => setCategory('All documents')}>All documents</Button>{categories.map((item) => <Button key={item} type="button" size="sm" variant={category === item ? 'primary' : 'outline'} onClick={() => setCategory(item)}>{item}</Button>)}</CardContent></Card>
        <Card><CardHeader className="border-b border-divider"><div className="flex items-start justify-between gap-3"><div><CardTitle>Document list</CardTitle><CardDescription className="mt-1">Metadata and workflow state only — no files are stored</CardDescription></div><Badge variant="brand"><FolderOpen />{visible.length} shown</Badge></div></CardHeader><CardContent className="divide-y divide-divider p-0">{visible.map((document) => <button key={document.id} type="button" onClick={() => setSelectedId(document.id)} className={cn('flex w-full items-start gap-3 px-5 py-4 text-left transition-colors', selectedId === document.id ? 'bg-brand-soft' : 'hover:bg-surface-app')}><span className="flex size-9 shrink-0 items-center justify-center rounded-md bg-surface-elevated text-metadata"><FileText className="size-4" /></span><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-supporting">{document.name}</p><p className="mt-1 text-xs text-metadata">{document.type} · {document.date} · {document.owner}</p><div className="mt-2 flex flex-wrap gap-2"><Badge variant={statusVariant[document.status]}>{document.status}</Badge><Badge variant="neutral">{document.review}</Badge></div></div><ChevronRight className="mt-2 size-4 text-disabled" /></button>)}</CardContent></Card>
      </div>

      <Card variant="elevated"><CardHeader className="border-b border-divider"><div className="flex items-start justify-between gap-3"><div><CardTitle>Document detail</CardTitle><CardDescription className="mt-1">Selected workflow record</CardDescription></div><Badge variant={statusVariant[selected.status]}>{selected.status}</Badge></div></CardHeader><CardContent className="space-y-5 pt-6"><div><p className="text-sm font-semibold text-supporting">{selected.name}</p><p className="mt-1 text-xs text-metadata">{selected.category}</p></div><dl className="space-y-3 text-sm">{[['Type',selected.type],['Date',selected.date],['Source / owner',selected.owner],['Review state',selected.review],['Responsible team',selected.team]].map(([label,value]) => <div key={label} className="flex justify-between gap-4"><dt className="text-metadata">{label}</dt><dd className="text-right font-medium text-supporting">{value}</dd></div>)}</dl><div className="rounded-md border border-border bg-input-background p-4"><p className="text-xs uppercase tracking-wider text-metadata">Document summary</p><p className="mt-2 text-sm leading-6 text-supporting">{selected.summary}</p></div><div className={cn('rounded-md border p-4', selected.status === 'Missing' ? 'border-critical/30 bg-critical-subtle' : 'border-brand-soft bg-surface-clinical')}><p className="text-xs uppercase tracking-wider text-metadata">Next workflow action</p><p className="mt-2 text-sm font-semibold text-supporting">{selected.next}</p></div><div className="flex gap-2 rounded-md border border-warning/30 bg-warning-subtle p-3 text-xs text-warning-strong"><AlertTriangle className="size-4 shrink-0" /><span>Clinical interpretation remains with the treating team. This view does not retrieve or transmit a document.</span></div></CardContent></Card>
    </div>
  </PageContainer>
}
