'use client'

import * as React from 'react'
import { AlertTriangle, ArrowRight, CheckCircle2, CircleDot, Clock3, FileText, FlaskConical, Network, Route, ShieldAlert, Stethoscope, UserRound, Users } from 'lucide-react'
import { PageContainer, PageHeader } from '@/components/shell/page-container'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { cn } from '@/lib/utils'
import { useDemoAccess } from '@/components/demo-access-provider'

type Status = 'Completed' | 'In progress' | 'Upcoming' | 'Awaiting review'
type Milestone = { id: string; label: string; date: string; owner: string; status: Status; context: string; next: string; icon: typeof UserRound }
const milestones: Milestone[] = [
  { id: 'registration', label: 'Registration', date: '18 Jun 2026', owner: 'Patient Access', status: 'Completed', context: 'Identity, contact, referral, and communication details captured for this fictional patient.', next: 'Proceed to clinical intake.', icon: UserRound },
  { id: 'intake', label: 'Nurse Intake', date: '23 Aug 2026 · 09:45', owner: 'Nurse Navigator', status: 'Completed', context: 'Symptoms, medications, allergy status, vitals, ECOG status, and safety checks documented.', next: 'Clinical assessment completed in Doctor OPD.', icon: CheckCircle2 },
  { id: 'opd', label: 'Doctor OPD', date: '23 Aug 2026 · 10:30', owner: 'Medical Oncologist', status: 'Completed', context: 'Treatment toxicity assessed; diagnosis, plan, investigations, and follow-up documented.', next: 'Review ordered diagnostic results.', icon: Stethoscope },
  { id: 'diagnostics', label: 'Diagnostics', date: '23 Aug 2026', owner: 'Lab and Radiology Review', status: 'Awaiting review', context: 'Fictional CBC includes critical ANC; staging CT report is available for clinician interpretation.', next: 'Responsible clinician reviews laboratory and radiology results.', icon: FlaskConical },
  { id: 'treatment', label: 'Treatment', date: 'Planned 31 Aug 2026', owner: 'Day Care Team', status: 'In progress', context: 'Cycle 3 readiness is being coordinated; no treatment is authorised by this prototype.', next: 'Complete clinician-led readiness clearance.', icon: CircleDot },
  { id: 'scribe', label: 'OPD Scribe', date: '23 Aug 2026 · 11:10', owner: 'Medical Oncologist', status: 'Completed', context: 'Fictional transcript reviewed and structured note approved in the demonstration workflow.', next: 'Maintain clinician-owned documentation.', icon: FileText },
  { id: 'nexus', label: 'NEXUS coordination', date: '23–30 Aug 2026', owner: 'Oncology Coordination Team', status: 'In progress', context: 'Open tasks have owners, due dates, workflow links, and explicit human review states.', next: 'Track diagnostic review, readiness, MDT, and patient follow-up.', icon: Network },
  { id: 'mdt', label: 'MDT / Tumour Board', date: '29 Aug 2026 · 08:00', owner: 'Tumour Board Coordinator', status: 'Upcoming', context: 'Structured case prepared for clinician-led multidisciplinary review.', next: 'Record MDT outcome and responsible-clinician actions.', icon: Users },
  { id: 'follow-up', label: 'Follow-up', date: '30 Aug 2026 · 10:30', owner: 'Medical Oncology', status: 'Upcoming', context: 'Review toxicity, diagnostic context, MDT outcome, and subsequent treatment planning.', next: 'Attend oncology follow-up or escalate symptoms earlier.', icon: Clock3 },
]
const statusVariant = { Completed: 'success', 'In progress': 'information', Upcoming: 'neutral', 'Awaiting review': 'warning' } as const
const upcoming = [
  ['Laboratory result review', 'Today · 11:30', 'Medical Oncology', 'High'], ['Treatment-cycle readiness', 'Before 31 Aug', 'Day Care Team', 'High'],
  ['MDT review and outcome', '29 Aug · 08:00', 'Tumour Board', 'Routine'], ['Oncology follow-up', '30 Aug · 10:30', 'Medical Oncologist', 'Routine'],
  ['Patient symptom follow-up', '25 Aug · 12:00', 'Nurse Navigator', 'Routine'],
]

export default function PatientJourneyPage() {
  const { events } = useDemoAccess()
  const [selectedId, setSelectedId] = React.useState('diagnostics')
  const selected = milestones.find((item) => item.id === selectedId) ?? milestones[0]
  return <PageContainer>
    <PageHeader title="Patient Journey" description="Track the patient's oncology pathway across clinical and coordination milestones." actions={<Badge variant="information">Fictional demo data</Badge>} />
    <Card className="mb-6"><CardHeader className="border-b border-divider"><CardTitle>Journey events and provenance</CardTitle><CardDescription>Shared demo events created across stakeholder workspaces</CardDescription></CardHeader><CardContent className="divide-y divide-divider p-0">{events.slice(0,30).map((event)=><div key={event.id} className="flex flex-wrap items-center gap-3 px-6 py-4"><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-supporting">{event.action}</p><p className="mt-1 text-xs text-metadata">{event.actor} · {event.role} · {event.timestamp}</p><p className="mt-1 text-xs text-metadata">Source: {event.source}{event.destination ? ` · Destination: ${event.destination}` : ''}</p></div><Badge variant={event.status==='Completed'?'success':'warning'}>{event.status ?? 'Recorded'}</Badge></div>)}</CardContent></Card>
    <div className="mb-6 flex items-start gap-3 rounded-lg border border-information/30 bg-information-subtle px-4 py-3 text-information-strong"><ShieldAlert className="mt-0.5 size-4 shrink-0" /><div><p className="text-sm font-medium">Workflow visualisation only</p><p className="mt-0.5 text-xs">All data is fictional. Decisions remain clinician-led; this prototype makes no autonomous treatment decision and has no EHR, HIS, PACS, or LIS integration.</p></div></div>
    <Card className="mb-6 bg-surface-clinical"><CardContent className="grid gap-5 p-5 sm:grid-cols-2 xl:grid-cols-5"><div className="flex items-center gap-3 sm:col-span-2"><span className="flex size-10 items-center justify-center rounded-full bg-surface"><UserRound className="size-5" /></span><div><p className="font-display font-semibold">Sunita Patil <span className="text-xs font-normal text-metadata">(Fictional)</span></p><p className="text-xs text-metadata">MRN DEMO-ONC-02481 · 39 years · Female</p></div></div><div><p className="text-xs uppercase tracking-wider text-metadata">Diagnosis / stage</p><p className="mt-1 text-sm font-medium text-supporting">Breast cancer · Stage IIA</p></div><div><p className="text-xs uppercase tracking-wider text-metadata">Current treatment</p><p className="mt-1 text-sm font-medium text-supporting">AC chemotherapy · C2D8</p></div><div><p className="text-xs uppercase tracking-wider text-metadata">Care team</p><p className="mt-1 text-sm font-medium text-supporting">Medical Oncology + Navigator</p></div></CardContent></Card>

    <Card className="mb-6"><CardHeader className="border-b border-divider"><div className="flex items-start justify-between gap-3"><div><CardTitle>Oncology journey timeline</CardTitle><CardDescription className="mt-1">Select a milestone to inspect ownership, context, and next action.</CardDescription></div><Badge variant="warning"><Route />Current: Diagnostics review</Badge></div></CardHeader><CardContent className="pt-6"><div className="overflow-x-auto pb-2"><ol className="flex min-w-[1000px] items-start">{milestones.map((milestone,index) => { const Icon = milestone.icon; const current = milestone.id === 'diagnostics'; return <li key={milestone.id} className="relative flex-1"><button type="button" onClick={() => setSelectedId(milestone.id)} className="group w-full text-left"><div className="flex items-center"><span className={cn('relative z-10 flex size-10 items-center justify-center rounded-full border-2', current ? 'border-primary bg-primary text-primary-foreground shadow-neu' : milestone.status === 'Completed' ? 'border-success bg-success-subtle text-success-strong' : 'border-border bg-surface text-metadata')}><Icon className="size-4" /></span>{index < milestones.length - 1 ? <span className={cn('h-0.5 flex-1', milestone.status === 'Completed' ? 'bg-success' : 'bg-border-emphasized')} /> : null}</div><div className={cn('mt-3 mr-3 rounded-md border p-3 transition-colors', selectedId === milestone.id ? 'border-brand bg-brand-soft' : 'border-transparent group-hover:bg-surface-app')}><p className="text-sm font-semibold text-supporting">{milestone.label}</p><p className="mt-1 text-xs text-metadata">{milestone.date}</p><Badge className="mt-2" variant={statusVariant[milestone.status]}>{milestone.status}</Badge></div></button></li> })}</ol></div></CardContent></Card>

    <div className="mb-6 grid gap-6 xl:grid-cols-3"><Card variant="elevated" className="xl:col-span-2"><CardHeader className="border-b border-divider"><div className="flex items-start justify-between gap-3"><div><CardTitle>{selected.label}</CardTitle><CardDescription className="mt-1">Selected milestone details</CardDescription></div><Badge variant={statusVariant[selected.status]}>{selected.status}</Badge></div></CardHeader><CardContent className="grid gap-5 pt-6 sm:grid-cols-2"><div><p className="text-xs uppercase tracking-wider text-metadata">Date</p><p className="mt-1 text-sm font-medium text-supporting">{selected.date}</p></div><div><p className="text-xs uppercase tracking-wider text-metadata">Owner</p><p className="mt-1 text-sm font-medium text-supporting">{selected.owner}</p></div><div className="sm:col-span-2"><p className="text-xs uppercase tracking-wider text-metadata">Clinical / operational context</p><p className="mt-2 text-sm leading-6 text-supporting">{selected.context}</p></div><div className="rounded-md border border-brand-soft bg-surface-clinical p-4 sm:col-span-2"><p className="text-xs uppercase tracking-wider text-metadata">Next workflow action</p><p className="mt-2 text-sm font-semibold text-supporting">{selected.next}</p></div></CardContent></Card><Card><CardHeader className="border-b border-divider"><CardTitle>Current position</CardTitle><CardDescription>Diagnostics review and readiness coordination</CardDescription></CardHeader><CardContent className="space-y-4 pt-6"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-full bg-warning-subtle text-warning-strong"><FlaskConical className="size-5" /></span><div><p className="text-sm font-semibold text-supporting">Diagnostics awaiting review</p><p className="text-xs text-metadata">Human interpretation required</p></div></div><div className="rounded-md border border-warning/30 bg-warning-subtle p-3 text-xs text-warning-strong">The journey position reflects workflow state only, not a clinical risk prediction or treatment authorisation.</div></CardContent></Card></div>

    <div className="grid gap-6 xl:grid-cols-3"><Card className="xl:col-span-2"><CardHeader className="border-b border-divider"><CardTitle>Upcoming care</CardTitle><CardDescription>Fictional scheduled and coordination items</CardDescription></CardHeader><CardContent className="divide-y divide-divider p-0">{upcoming.map(([task,due,owner,priority]) => <div key={task} className="flex flex-wrap items-center gap-3 px-6 py-4"><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-supporting">{task}</p><p className="mt-1 text-xs text-metadata">{owner} · {due}</p></div><Badge variant={priority === 'High' ? 'warning' : 'neutral'}>{priority}</Badge><Button type="button" variant="ghost" size="sm">View workflow<ArrowRight /></Button></div>)}</CardContent></Card><Card><CardHeader className="border-b border-divider"><CardTitle>Barriers / workflow risks</CardTitle><CardDescription>Operational issues requiring human follow-up</CardDescription></CardHeader><CardContent className="space-y-3 pt-6">{[['Pending laboratory review','Critical fictional ANC requires clinician interpretation'],['Treatment readiness incomplete','Clearance not yet recorded'],['Patient follow-up required','Symptom check scheduled for 25 Aug']].map(([title,detail]) => <div key={title} className="rounded-md border border-warning/30 bg-warning-subtle p-3"><div className="flex gap-2"><AlertTriangle className="mt-0.5 size-4 shrink-0 text-warning-strong" /><div><p className="text-sm font-semibold text-warning-strong">{title}</p><p className="mt-1 text-xs text-warning-strong">{detail}</p></div></div></div>)}</CardContent></Card></div>
  </PageContainer>
}
