'use client'

import * as React from 'react'
import { AlertCircle, CheckCircle2, ClipboardPlus, FileCheck2, FlaskConical, History, ListChecks, Stethoscope, UserRound } from 'lucide-react'
import { PageContainer, PageHeader } from '@/components/shell/page-container'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { cn } from '@/lib/utils'
import { useDemoAccess } from '@/components/demo-access-provider'
import { ClinicianAssistiveTools, DiagnosisAndTreatment, DoctorClinicalReview, PreConsultationHandoff } from '@/components/doctor-opd-enhancements'
import { DoctorPatientSearchAndSummary } from '@/components/doctor-patient-summary'
import OpdScribePage from '@/app/opd-scribe/page'

type Values = { complaint: string; assessment: string; diagnosis: string; stage: string; plan: string; followUp: string; reviewConfirmed: boolean }
type Errors = Partial<Record<keyof Values, string>>
const initialValues: Values = {
  complaint: 'Fatigue and intermittent nausea following cycle 2 of adjuvant chemotherapy. No fever, dyspnoea, chest pain, or persistent vomiting.',
  assessment: 'ECOG 1. Haemodynamically stable. Mild pallor and reduced oral intake without clinical dehydration. No palpable lymphadenopathy. Surgical wound healed.',
  diagnosis: 'Left breast invasive ductal carcinoma, ER/PR positive, HER2 negative',
  stage: 'pT2N0M0 · Stage IIA',
  plan: 'Continue adjuvant AC chemotherapy if laboratory parameters remain acceptable. Optimise antiemetic schedule, reinforce hydration and neutropenic precautions, and review dietitian referral.',
  followUp: 'Medical oncology review in 1 week before cycle 3, or earlier for fever ≥38 °C, uncontrolled vomiting, breathlessness, bleeding, or clinical deterioration.',
  reviewConfirmed: false,
}
const controlClass = 'flex h-10 w-full rounded-md border border-input bg-input-background px-3 py-2 text-sm text-foreground shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1'

function Section({ icon: Icon, title, description, children }: { icon: typeof UserRound; title: string; description: string; children: React.ReactNode }) {
  return <Card><CardHeader className="border-b border-divider pb-4"><div className="flex gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-md bg-brand-soft text-supporting"><Icon className="size-4" /></span><div><CardTitle>{title}</CardTitle><CardDescription className="mt-1">{description}</CardDescription></div></div></CardHeader><CardContent className="pt-6">{children}</CardContent></Card>
}
function Label({ htmlFor, children, required }: { htmlFor: string; children: React.ReactNode; required?: boolean }) { return <label htmlFor={htmlFor} className="text-sm font-medium text-supporting">{children}{required ? <span className="ml-1 text-critical">*</span> : null}</label> }
function ErrorText({ id, text }: { id: string; text?: string }) { return text ? <p id={id} className="flex items-center gap-1.5 text-xs text-critical-strong"><AlertCircle className="size-3.5" />{text}</p> : null }

export default function DoctorOpdPage() {
  const { role, performAction, tasks, workflow } = useDemoAccess()
  const isSurgicalOncologist = role.roleId === 'surgical-oncology'
  const isRadiationOncologist = role.roleId === 'radiation-oncology'
  const [values, setValues] = React.useState(initialValues)
  const [errors, setErrors] = React.useState<Errors>({})
  const [complete, setComplete] = React.useState(false)
  const [orders, setOrders] = React.useState(['Complete blood count', 'Renal and liver function panel'])
  const [reviewedTasks,setReviewedTasks] = React.useState<string[]>([])
  const update = <K extends keyof Values>(field: K, value: Values[K]) => { setValues((current) => ({ ...current, [field]: value })); setErrors((current) => ({ ...current, [field]: undefined })); setComplete(false) }
  const submit = (event: React.FormEvent) => { event.preventDefault(); const next: Errors = {}; (['complaint','assessment','diagnosis','stage','plan','followUp'] as Array<keyof Values>).forEach((field) => { if (!values[field]) next[field] = 'This clinical field is required.' }); if (!values.reviewConfirmed) next.reviewConfirmed = 'Clinician review is required before completion.'; setErrors(next); const valid=Object.keys(next).length === 0; setComplete(valid); if(valid)performAction('complete-opd','Doctor consultation completed','Doctor OPD',{destination:'Treatment Planning',status:'Completed',owner:'Medical Oncology',nextAction:'Review diagnostics and treatment clearance'}); if (Object.keys(next).length) requestAnimationFrame(() => document.querySelector<HTMLElement>('[aria-invalid="true"]')?.focus()) }
  const area = (field: keyof Values) => ({ 'aria-invalid': Boolean(errors[field]), className: cn(controlClass, 'h-auto resize-y', errors[field] && 'border-critical') })
  return <PageContainer>
    <PageHeader title="Consultation" description="Review the oncology encounter, document clinical decisions, and complete the consultation." actions={<a href="#consultation-scribe" className="inline-flex min-h-10 items-center rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground">Start Consultation</a>} />
    <DoctorPatientSearchAndSummary />
    <PreConsultationHandoff />
    {tasks.filter((task)=>['Doctor OPD','Medical Oncology','Treatment Planning'].includes(task.destination)).slice(0,4).map((task)=><div key={task.id} className="mb-4 flex flex-wrap items-center gap-3 rounded-md border border-information/30 bg-information-subtle p-3"><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-information-strong">{task.task}</p><div className="mt-2 grid gap-2 text-xs text-information-strong sm:grid-cols-4"><p><strong>Owner:</strong> {task.owner??'Medical Oncology'}</p><p><strong>Status:</strong> {reviewedTasks.includes(task.id)?'Reviewed':task.status}</p><p><strong>Priority:</strong> {task.priority??'Routine'}</p><p><strong>Next action:</strong> {task.nextAction??'Review handoff'}</p></div></div><Badge variant={reviewedTasks.includes(task.id)?'success':'warning'}>{reviewedTasks.includes(task.id)?'Reviewed':task.status}</Badge><Button type="button" size="sm" variant="outline" onClick={()=>{setReviewedTasks((current)=>current.includes(task.id)?current:[...current,task.id]);performAction('review-results',task.destination==='Treatment Planning'?'MDT recommendation reviewed':'Diagnostic result reviewed','Doctor OPD',{status:'Completed'})}}>{task.destination==='Treatment Planning'?'Review MDT recommendation':task.destination==='Doctor OPD'?'Review Nurse Handoff':'Review Diagnostic Result'}</Button></div>)}
    {complete ? <div role="status" className="mb-6 flex gap-3 rounded-lg border border-success/30 bg-success-subtle px-4 py-3 text-success-strong"><CheckCircle2 className="mt-0.5 size-5" /><div><p className="text-sm font-semibold">Consultation validated as complete</p></div></div> : null}
    <form id="doctor-full-record" onSubmit={submit} noValidate className="space-y-6 scroll-mt-6">
      <Section icon={History} title="Oncology history" description="Key disease and treatment context for this encounter."><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Primary','Left breast invasive ductal carcinoma'],['Biology','ER/PR positive · HER2 negative'],['Surgery','Lumpectomy · June 2026'],['Systemic therapy','Adjuvant AC · cycle 2']].map(([label,value]) => <div key={label} className="rounded-md border border-border bg-input-background p-3"><p className="text-xs text-metadata">{label}</p><p className="mt-1 text-sm font-medium text-supporting">{value}</p></div>)}</div></Section>
      {isSurgicalOncologist ? <Section icon={Stethoscope} title="Surgical review" description="Document surgical assessment using the existing consultation workflow."><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[['Tumour / site examination','Left breast and axillary examination'],['Resectability assessment','Review required'],['Previous surgery','Lumpectomy · June 2026'],['Previous systemic therapy','Adjuvant AC · cycle 2'],['Previous radiotherapy','None documented'],['Relevant imaging review','Report available for clinician review'],['Pathology review','Pathology report available'],['Surgical anatomy / site','Left breast · site annotation available'],['Proposed procedure','To be finalized after imaging review'],['Reconstruction requirement','To be assessed'],['Operative concerns','Clinician documentation required'],['Further investigations','Confirm after imaging and pathology review'],['MDT requirement','Review if surgical approach changes']].map(([label,value])=><label key={label} className="text-xs font-medium text-metadata">{label}<Input className="mt-1" defaultValue={value}/></label>)}</div></Section> : null}
      {isRadiationOncologist ? <Section icon={Stethoscope} title="Radiation Oncology review" description="Document radiation indication, suitability, and planning context."><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[['Radiation indication','Adjuvant'],['Previous radiation','No'],['Previous treatment site / course','None documented'],['Overlap concern','No previous course documented; clinician review required'],['Previous surgery','Lumpectomy · June 2026'],['Systemic therapy','Adjuvant AC · cycle 2'],['Pathology','Grade 2 invasive ductal carcinoma · ER/PR positive · HER2 negative'],['Imaging review','Report available for target and extent review'],['Target-site examination','Left breast and regional nodal examination'],['Performance status','ECOG 1'],['Radiation suitability','Needs further evaluation'],['Concurrent therapy','To be discussed / pending'],['Precautions / concerns','Clinician-entered review required'],['Additional requirements','Planning imaging · pathology review · consent · MDT if needed']].map(([label,value])=><label key={label} className="text-xs font-medium text-metadata">{label}<Input className="mt-1" defaultValue={value}/></label>)}</div></Section> : null}
      <DoctorClinicalReview />
      <Section icon={Stethoscope} title="Presenting complaint and assessment" description="Document the current concern and clinician findings."><div className="grid gap-5 lg:grid-cols-2"><div className="space-y-2"><Label htmlFor="complaint" required>Presenting complaint</Label><textarea id="complaint" rows={5} value={values.complaint} onChange={(e) => update('complaint', e.target.value)} {...area('complaint')} /><ErrorText id="complaint-error" text={errors.complaint} /></div><div className="space-y-2"><Label htmlFor="assessment" required>Clinical assessment</Label><textarea id="assessment" rows={5} value={values.assessment} onChange={(e) => update('assessment', e.target.value)} {...area('assessment')} /><ErrorText id="assessment-error" text={errors.assessment} /></div></div></Section>
      <div id="staging" className="scroll-mt-6"><Section icon={ClipboardPlus} title="Diagnosis" description="Confirm the working oncology diagnosis and stage."><div className="grid gap-5 sm:grid-cols-3"><div className="space-y-2 sm:col-span-2"><Label htmlFor="diagnosis" required>Diagnosis</Label><Input id="diagnosis" value={values.diagnosis} onChange={(e) => update('diagnosis', e.target.value)} aria-invalid={Boolean(errors.diagnosis)} className={cn(errors.diagnosis && 'border-critical')} /><ErrorText id="diagnosis-error" text={errors.diagnosis} /></div><div className="space-y-2"><Label htmlFor="stage" required>TNM / stage</Label><Input id="stage" value={values.stage} onChange={(e) => update('stage', e.target.value)} aria-invalid={Boolean(errors.stage)} className={cn(errors.stage && 'border-critical')} /><ErrorText id="stage-error" text={errors.stage} /></div></div></Section></div>
      <DiagnosisAndTreatment />
      <ClinicianAssistiveTools />
      <Section icon={ListChecks} title="Treatment plan" description="Record the agreed plan and supportive-care instructions."><div className="space-y-2"><Label htmlFor="plan" required>Plan</Label><textarea id="plan" rows={5} value={values.plan} onChange={(e) => update('plan', e.target.value)} {...area('plan')} /><ErrorText id="plan-error" text={errors.plan} /></div></Section>
      <Section icon={FlaskConical} title="Investigations and orders" description="Fictional orders proposed for this encounter."><div className="grid gap-3 sm:grid-cols-2">{['Complete blood count','Renal and liver function panel','CT chest / abdomen / pelvis','ECG before next cycle','Dietitian consultation'].map((order) => <label key={order} className={cn('flex items-center gap-3 rounded-md border p-3 text-sm', orders.includes(order) ? 'border-brand bg-brand-soft' : 'border-border bg-input-background')}><input type="checkbox" checked={orders.includes(order)} onChange={() => setOrders((current) => current.includes(order) ? current.filter((item) => item !== order) : [...current, order])} className="size-4 accent-primary" />{order}</label>)}</div><div className="mt-4 flex flex-wrap gap-2"><Button type="button" onClick={()=>performAction('order-investigations','Laboratory and radiology investigations ordered','Doctor OPD',{destination:'Lab / Radiology',status:'Ordered',owner:'Diagnostics teams',priority:'Routine',nextAction:'Schedule and complete diagnostics'})}>Order investigations</Button><Button type="button" variant="outline" onClick={()=>performAction('send-mdt','Case sent to MDT for multidisciplinary review','Doctor OPD',{destination:'MDT / Tumour Board',status:'Awaiting review',owner:'MDT Coordinator',priority:'High',nextAction:'Open MDT case and record recommendation'})}>Send to MDT</Button><Button type="button" variant="outline" onClick={()=>performAction('draft-care-plan','Treatment plan ready for financial estimate','Doctor OPD',{destination:'Conversion / Finance',status:'Estimate required',owner:'Conversion / Finance',priority:'Routine',nextAction:'Prepare estimate and complete financial counselling'})}>Send Treatment Plan to Finance</Button><Badge variant="warning">Clearance: {workflow.treatmentClearance}</Badge></div></Section>
      <Section icon={FileCheck2} title="Follow-up and completion" description="Set review timing and confirm clinician ownership."><div className="space-y-5"><div className="space-y-2"><Label htmlFor="followUp" required>Follow-up plan and safety-net advice</Label><textarea id="followUp" rows={4} value={values.followUp} onChange={(e) => update('followUp', e.target.value)} {...area('followUp')} /><ErrorText id="followUp-error" text={errors.followUp} /></div><label className={cn('flex items-start gap-3 text-sm text-supporting', errors.reviewConfirmed && 'text-critical-strong')}><input type="checkbox" checked={values.reviewConfirmed} onChange={(e) => update('reviewConfirmed', e.target.checked)} aria-invalid={Boolean(errors.reviewConfirmed)} className="mt-0.5 size-4 accent-primary" /><span>I reviewed the encounter, diagnosis, plan, orders, and safety-net advice. <span className="text-critical">*</span></span></label><ErrorText id="reviewConfirmed-error" text={errors.reviewConfirmed} /></div></Section>
      <div className="sticky bottom-0 z-10 -mx-4 flex flex-col-reverse gap-3 border-t border-border bg-surface/95 px-4 py-4 shadow-soft backdrop-blur-sm sm:mx-0 sm:flex-row sm:items-center sm:justify-end sm:rounded-lg sm:border"><div className="flex gap-2"><Button type="button" variant="secondary" onClick={() => { setValues(initialValues); setErrors({}); setComplete(false) }}>Reset form</Button><Button type="submit">Review / Complete</Button></div></div>
    </form>
    <section id="consultation-scribe" className="mt-8 scroll-mt-6 border-t border-divider pt-8"><OpdScribePage /></section>
  </PageContainer>
}
