"""
Fictional QA scenario content for tools/generate_scenario_docs.py. Every name, date, MRN and
clinical detail below is fabricated for CCA workflow testing only, mirroring the structure of
the user-supplied CCA_Demo_Case_Maya_Iyer_All_In_One.pdf: one primary disease episode per
scenario, one deliberate site/laterality contradiction (for NEXUS), one deliberate abnormal
lab result before a second treatment cycle (for the Lab -> Day-Care -> Medical Oncology ->
Care Coordinator closed-loop hold/delay workflow), and a full source-document trail.
"""

SCENARIOS = {
    "lung": [
        {
            "filename": "01_Referral_Letter.pdf",
            "title": "Referral Letter",
            "subtitle": "Arjun Verma | Lung Cancer Scenario",
            "rows": [
                ("To", "CCA Oncology Centre"),
                ("From", "Dr. R. Kulkarni, Pulmonologist, Horizon Chest Clinic"),
                ("Patient", "Arjun Verma, DOB 03-Jun-1968"),
                ("Date", "01-Sep-2026"),
                ("Reason", "Persistent cough with streaky hemoptysis for 6 weeks; outside CT shows a right upper lobe mass."),
                ("Note", "Please evaluate the left lung mass and advise oncology management."),
                ("Attached", "Outside CT chest report, bronchoscopy biopsy report, molecular panel."),
                ("Important QA note", "The single phrase 'left lung' above is intentionally incorrect. All authoritative diagnostic evidence in this scenario is RIGHT-sided. The system should preserve the source and flag the discordance rather than silently editing it."),
            ],
        },
        {
            "filename": "02_Outside_CT_Chest_Summary.pdf",
            "title": "Outside CT Chest Summary",
            "subtitle": "Arjun Verma | Lung Cancer Scenario",
            "rows": [
                ("Patient", "Arjun Verma"),
                ("Study date", "28-Aug-2026"),
                ("Side", "Right"),
                ("Finding", "Spiculated mass in the right upper lobe measuring approximately 4.2 cm, with right hilar lymphadenopathy."),
                ("Impression", "Suspicious right upper lobe mass concerning for primary lung malignancy; tissue diagnosis recommended."),
            ],
        },
        {
            "filename": "03_Bronchoscopy_Biopsy_Pathology.pdf",
            "title": "Bronchoscopy Biopsy Pathology Report",
            "subtitle": "Arjun Verma | Lung Cancer Scenario",
            "rows": [
                ("Patient", "Arjun Verma"),
                ("Specimen", "Right upper lobe endobronchial biopsy"),
                ("Histology", "Adenocarcinoma"),
                ("Differentiation", "Moderately differentiated"),
                ("Status", "Final outside report; hospital pathology verification required before use as verified fact."),
            ],
        },
        {
            "filename": "04_Molecular_Biomarker_Report.pdf",
            "title": "Molecular / Biomarker Report",
            "subtitle": "Arjun Verma | Lung Cancer Scenario",
            "rows": [
                ("Patient", "Arjun Verma"),
                ("EGFR", "Exon 19 deletion detected - Positive"),
                ("ALK", "Negative (FISH)"),
                ("ROS1", "Negative (FISH)"),
                ("PD-L1 TPS", "Approximately 40%"),
                ("Status", "Final outside molecular report; hospital verification required."),
            ],
        },
        {
            "filename": "05_Baseline_Laboratory_Report.pdf",
            "title": "Baseline Laboratory Report",
            "subtitle": "Arjun Verma | Lung Cancer Scenario",
            "rows": [
                ("Patient", "Arjun Verma"),
                ("Hb", "13.8 g/dL"),
                ("ANC", "4.1 x10^9/L"),
                ("Platelets", "245 x10^9/L"),
                ("Creatinine", "0.9 mg/dL"),
                ("AST / ALT", "22 / 25 U/L"),
                ("Interpretation", "Values are fictional and intended only to test baseline treatment-readiness workflows."),
            ],
        },
        {
            "filename": "06_PET_CT_Staging_Report.pdf",
            "title": "PET-CT Staging Report",
            "subtitle": "Arjun Verma | Lung Cancer Scenario",
            "rows": [
                ("Patient", "Arjun Verma"),
                ("Date", "03-Sep-2026"),
                ("Primary", "Hypermetabolic right upper lobe mass, consistent with known primary."),
                ("Nodes", "Hypermetabolic right hilar (station 10R) node; mediastinal nodes not involved."),
                ("Distant", "No hypermetabolic distant metastatic disease identified."),
                ("Impression", "Findings consistent with cT2bN1M0 right upper lobe non-small cell lung carcinoma; no distant metastasis on this examination."),
            ],
        },
        {
            "filename": "07_Pre_Cycle2_Renal_Panel.pdf",
            "title": "Pre-Cycle 2 Renal Function Panel",
            "subtitle": "Arjun Verma | Lung Cancer Scenario",
            "rows": [
                ("Patient", "Arjun Verma"),
                ("Date", "24-Sep-2026"),
                ("Creatinine", "2.1 mg/dL"),
                ("eGFR", "Approximately 32 mL/min/1.73m^2"),
                ("Workflow flag", "Renal function is intentionally reduced below the level needed for safe carboplatin (Calvert formula) dosing. Treatment must wait for clinician review."),
            ],
        },
        {
            "filename": "08_Repeat_Renal_Panel_After_Delay.pdf",
            "title": "Repeat Renal Function Panel After Delay",
            "subtitle": "Arjun Verma | Lung Cancer Scenario",
            "rows": [
                ("Patient", "Arjun Verma"),
                ("Date", "01-Oct-2026"),
                ("Creatinine", "1.0 mg/dL"),
                ("eGFR", "Approximately 68 mL/min/1.73m^2"),
                ("Workflow flag", "Result is intended to allow clinician reassessment/clearance for the rescheduled cycle."),
            ],
        },
        {
            "filename": "09_Response_CT_Chest.pdf",
            "title": "Response CT Chest",
            "subtitle": "Arjun Verma | Lung Cancer Scenario",
            "rows": [
                ("Patient", "Arjun Verma"),
                ("Date", "10-Dec-2026"),
                ("Comparison", "Baseline right upper lobe mass approximately 4.2 cm."),
                ("Current finding", "Right upper lobe mass reduced to approximately 2.1 cm; right hilar node no longer pathologically enlarged."),
                ("Impression", "Marked interval response to neoadjuvant systemic therapy; no new distant finding."),
            ],
        },
        {
            "filename": "10_Operative_Note.pdf",
            "title": "Operative Note",
            "subtitle": "Arjun Verma | Lung Cancer Scenario",
            "rows": [
                ("Patient", "Arjun Verma"),
                ("Date", "22-Dec-2026"),
                ("Procedure", "Right upper lobectomy with mediastinal lymph node dissection"),
                ("Specimens", "Lobectomy specimen with oriented margins; mediastinal and hilar nodal stations"),
                ("Outcome", "Procedure completed without major intraoperative complication in this fictional record."),
            ],
        },
        {
            "filename": "11_Final_Surgical_Pathology.pdf",
            "title": "Final Surgical Pathology",
            "subtitle": "Arjun Verma | Lung Cancer Scenario",
            "rows": [
                ("Patient", "Arjun Verma"),
                ("Specimen", "Right upper lobectomy and lymph node dissection"),
                ("Residual invasive adenocarcinoma", "1.8 cm"),
                ("Margins", "Negative"),
                ("Nodes", "0 / 8 involved"),
                ("Post-treatment pathologic TNM", "ypT1cN0"),
                ("Status", "Final fictional report; should supersede, not erase, earlier pathologic/staging evidence."),
            ],
        },
    ],
    "lymphoma": [
        {
            "filename": "01_Referral_Letter.pdf",
            "title": "Referral Letter",
            "subtitle": "Kavya Reddy | Lymphoma Scenario",
            "rows": [
                ("To", "CCA Oncology Centre"),
                ("From", "Dr. N. Rao, General Physician, Wellview Clinic"),
                ("Patient", "Kavya Reddy, DOB 19-Nov-1985"),
                ("Date", "01-Sep-2026"),
                ("Reason", "Painless enlarging neck swelling for 2 months with drenching night sweats and 6 kg weight loss."),
                ("Note", "Please evaluate the right cervical lymphadenopathy and advise oncology management."),
                ("Attached", "Excisional lymph node biopsy report, PET-CT report."),
                ("Important QA note", "The single phrase 'right cervical' above is intentionally incorrect. All authoritative diagnostic evidence in this scenario is LEFT-sided (left cervical and left axillary). The system should preserve the source and flag the discordance rather than silently editing it."),
            ],
        },
        {
            "filename": "02_Excisional_Node_Biopsy_Pathology.pdf",
            "title": "Excisional Lymph Node Biopsy Pathology Report",
            "subtitle": "Kavya Reddy | Lymphoma Scenario",
            "rows": [
                ("Patient", "Kavya Reddy"),
                ("Specimen", "Left cervical lymph node, excisional biopsy"),
                ("Histology", "Diffuse large B-cell lymphoma"),
                ("Subtype", "Germinal centre B-cell (GCB) type"),
                ("Status", "Final outside report; hospital pathology verification required before use as verified fact."),
            ],
        },
        {
            "filename": "03_Immunohistochemistry_Report.pdf",
            "title": "Immunohistochemistry / Biomarker Report",
            "subtitle": "Kavya Reddy | Lymphoma Scenario",
            "rows": [
                ("Patient", "Kavya Reddy"),
                ("CD20", "Positive"),
                ("CD10", "Positive"),
                ("BCL6", "Positive"),
                ("MYC", "Low expression, no rearrangement detected"),
                ("Ki-67", "Approximately 85%"),
                ("Status", "Final outside report; hospital verification required."),
            ],
        },
        {
            "filename": "04_Baseline_Laboratory_Report.pdf",
            "title": "Baseline Laboratory Report",
            "subtitle": "Kavya Reddy | Lymphoma Scenario",
            "rows": [
                ("Patient", "Kavya Reddy"),
                ("Hb", "11.4 g/dL"),
                ("ANC", "3.2 x10^9/L"),
                ("Platelets", "260 x10^9/L"),
                ("LDH", "Elevated at 410 U/L (institutional upper limit 250 U/L)"),
                ("Renal / liver profile", "Within institutional treatment range."),
                ("Interpretation", "Values are fictional and intended only to test baseline treatment-readiness workflows; elevated LDH is a recognized adverse prognostic factor in this disease."),
            ],
        },
        {
            "filename": "05_Baseline_Echocardiogram.pdf",
            "title": "Baseline Echocardiogram",
            "subtitle": "Kavya Reddy | Lymphoma Scenario",
            "rows": [
                ("Patient", "Kavya Reddy"),
                ("Date", "03-Sep-2026"),
                ("LVEF", "60%"),
                ("Impression", "Preserved left ventricular systolic function in this fictional demo; baseline prior to anthracycline-containing regimen."),
            ],
        },
        {
            "filename": "06_PET_CT_Staging_Report.pdf",
            "title": "PET-CT Staging Report",
            "subtitle": "Kavya Reddy | Lymphoma Scenario",
            "rows": [
                ("Patient", "Kavya Reddy"),
                ("Date", "04-Sep-2026"),
                ("Findings", "Hypermetabolic left cervical, left axillary, and splenic lesions."),
                ("Distant", "No hypermetabolic disease below the diaphragm outside the spleen; no hepatic or pulmonary involvement."),
                ("Impression", "Findings consistent with Ann Arbor Stage III diffuse large B-cell lymphoma involving both sides of the diaphragm-adjacent nodal groups and spleen."),
            ],
        },
        {
            "filename": "07_Pre_Cycle2_CBC.pdf",
            "title": "Pre-Cycle 2 CBC",
            "subtitle": "Kavya Reddy | Lymphoma Scenario",
            "rows": [
                ("Patient", "Kavya Reddy"),
                ("Date", "22-Sep-2026"),
                ("Hb", "10.1 g/dL"),
                ("ANC", "2.8 x10^9/L"),
                ("Platelets", "68 x10^9/L"),
                ("Workflow flag", "Platelet count is intentionally below the demo institution's configured treatment-clearance threshold for R-CHOP administration. Treatment must wait for clinician review."),
            ],
        },
        {
            "filename": "08_Repeat_CBC_After_Delay.pdf",
            "title": "Repeat CBC After Delay",
            "subtitle": "Kavya Reddy | Lymphoma Scenario",
            "rows": [
                ("Patient", "Kavya Reddy"),
                ("Date", "29-Sep-2026"),
                ("Platelets", "165 x10^9/L"),
                ("ANC", "3.0 x10^9/L"),
                ("Workflow flag", "Result is intended to allow clinician reassessment/clearance for the rescheduled cycle."),
            ],
        },
        {
            "filename": "09_Interim_Response_PET_CT.pdf",
            "title": "Interim Response PET-CT",
            "subtitle": "Kavya Reddy | Lymphoma Scenario",
            "rows": [
                ("Patient", "Kavya Reddy"),
                ("Date", "15-Dec-2026"),
                ("Comparison", "Baseline hypermetabolic left cervical, left axillary and splenic lesions."),
                ("Current finding", "Marked reduction in size and metabolic activity of all previously noted sites; Deauville score 2."),
                ("Impression", "Complete metabolic response after planned R-CHOP cycles; no new hypermetabolic disease."),
            ],
        },
    ],
    "cervical": [
        {
            "filename": "01_Referral_Letter.pdf",
            "title": "Referral Letter",
            "subtitle": "Sunita Deshmukh | Cervical Cancer Scenario",
            "rows": [
                ("To", "CCA Oncology Centre"),
                ("From", "Dr. P. Joshi, Gynaecologist, Lakeview Women's Clinic"),
                ("Patient", "Sunita Deshmukh, DOB 14-Apr-1975"),
                ("Date", "01-Sep-2026"),
                ("Reason", "Postcoital bleeding for 3 months; cervical biopsy showing malignancy."),
                ("Note", "Please evaluate the endometrial mass and advise oncology management."),
                ("Attached", "Cervical biopsy report, HPV test, pelvic MRI report."),
                ("Important QA note", "The single phrase 'endometrial mass' above is intentionally incorrect. All authoritative diagnostic evidence in this scenario is CERVICAL, not endometrial. The system should preserve the source and flag the discordance rather than silently editing it."),
            ],
        },
        {
            "filename": "02_Cervical_Biopsy_Pathology.pdf",
            "title": "Cervical Biopsy Pathology Report",
            "subtitle": "Sunita Deshmukh | Cervical Cancer Scenario",
            "rows": [
                ("Patient", "Sunita Deshmukh"),
                ("Specimen", "Cervical punch biopsy"),
                ("Histology", "Squamous cell carcinoma of the cervix"),
                ("Differentiation", "Moderately differentiated"),
                ("Status", "Final outside report; hospital pathology verification required before use as verified fact."),
            ],
        },
        {
            "filename": "03_HPV_Test_Report.pdf",
            "title": "HPV Test Report",
            "subtitle": "Sunita Deshmukh | Cervical Cancer Scenario",
            "rows": [
                ("Patient", "Sunita Deshmukh"),
                ("Test", "High-risk HPV genotyping"),
                ("Result", "HPV-16 detected, high-risk positive"),
                ("Status", "Final outside report; hospital verification required."),
            ],
        },
        {
            "filename": "04_Pelvic_MRI_Report.pdf",
            "title": "Pelvic MRI Report",
            "subtitle": "Sunita Deshmukh | Cervical Cancer Scenario",
            "rows": [
                ("Patient", "Sunita Deshmukh"),
                ("Date", "28-Aug-2026"),
                ("Finding", "Cervical mass measuring approximately 4.5 cm with left parametrial extension."),
                ("Hydronephrosis", "None identified."),
                ("Impression", "Findings consistent with locally advanced cervical carcinoma, clinical stage FIGO IIB."),
            ],
        },
        {
            "filename": "05_PET_CT_Staging_Report.pdf",
            "title": "PET-CT Staging Report",
            "subtitle": "Sunita Deshmukh | Cervical Cancer Scenario",
            "rows": [
                ("Patient", "Sunita Deshmukh"),
                ("Date", "02-Sep-2026"),
                ("Findings", "Hypermetabolic left pelvic sidewall lymph nodes; primary cervical mass hypermetabolic."),
                ("Distant", "No hypermetabolic distant metastatic disease identified."),
                ("Impression", "Locally advanced cervical carcinoma with pelvic nodal involvement; no distant metastasis on this examination."),
            ],
        },
        {
            "filename": "06_Baseline_Laboratory_Report.pdf",
            "title": "Baseline Laboratory Report",
            "subtitle": "Sunita Deshmukh | Cervical Cancer Scenario",
            "rows": [
                ("Patient", "Sunita Deshmukh"),
                ("Hb", "11.8 g/dL"),
                ("ANC", "3.9 x10^9/L"),
                ("Platelets", "290 x10^9/L"),
                ("Creatinine", "0.8 mg/dL"),
                ("Interpretation", "Values are fictional and intended only to test baseline treatment-readiness workflows before cisplatin-based chemoradiation."),
            ],
        },
        {
            "filename": "07_Pre_Week3_CBC.pdf",
            "title": "Pre-Week-3 Cisplatin CBC",
            "subtitle": "Sunita Deshmukh | Cervical Cancer Scenario",
            "rows": [
                ("Patient", "Sunita Deshmukh"),
                ("Date", "22-Sep-2026"),
                ("Hb", "7.6 g/dL"),
                ("Platelets", "205 x10^9/L"),
                ("Workflow flag", "Haemoglobin is intentionally below the demo institution's configured treatment-clearance threshold for concurrent weekly cisplatin. Treatment must wait for clinician review."),
            ],
        },
        {
            "filename": "08_Repeat_CBC_After_Transfusion.pdf",
            "title": "Repeat CBC After Transfusion",
            "subtitle": "Sunita Deshmukh | Cervical Cancer Scenario",
            "rows": [
                ("Patient", "Sunita Deshmukh"),
                ("Date", "25-Sep-2026"),
                ("Hb", "10.2 g/dL"),
                ("Platelets", "215 x10^9/L"),
                ("Workflow flag", "Result is intended to allow clinician reassessment/clearance for the rescheduled weekly cisplatin dose."),
            ],
        },
        {
            "filename": "09_Response_Pelvic_MRI.pdf",
            "title": "Response Pelvic MRI",
            "subtitle": "Sunita Deshmukh | Cervical Cancer Scenario",
            "rows": [
                ("Patient", "Sunita Deshmukh"),
                ("Date", "20-Nov-2026"),
                ("Comparison", "Baseline cervical mass approximately 4.5 cm with parametrial extension."),
                ("Current finding", "Marked reduction of cervical mass to approximately 1.2 cm; parametrial extension no longer identified."),
                ("Impression", "Marked interval response following concurrent chemoradiation; no new pelvic or distant finding."),
            ],
        },
    ],
}
